/**
 * Data-formatting utilities for the "My name is..." attribute tiles.
 * Abbreviates positions, nationalities, and league names to prevent text overflow
 * in the compact attribute cells.
 */

// ── Position Abbreviations ──────────────────────────────────────────────

const POSITION_MAP: Record<string, string> = {
  // Database values (the actual values in players_db_v1.json)
  Attack: 'ATT',
  Defender: 'DEF',
  Goalkeeper: 'GK',
  Midfield: 'MID',
  Missing: 'N/A',

  // Extended positions (in case data evolves)
  'Center Back': 'CB',
  'Centre-Back': 'CB',
  'Left Back': 'LB',
  'Left-Back': 'LB',
  'Right Back': 'RB',
  'Right-Back': 'RB',
  'Defensive Midfield': 'CDM',
  'Defensive Midfielder': 'CDM',
  'Central Midfield': 'CM',
  'Central Midfielder': 'CM',
  'Attacking Midfield': 'CAM',
  'Attacking Midfielder': 'CAM',
  'Right Winger': 'RW',
  'Left Winger': 'LW',
  'Right Wing': 'RW',
  'Left Wing': 'LW',
  Striker: 'ST',
  'Center Forward': 'CF',
  'Centre-Forward': 'CF',
  Forward: 'FWD',
  'Second Striker': 'SS',
};

export function formatPosition(position: string): string {
  return POSITION_MAP[position] ?? position.substring(0, 3).toUpperCase();
}

// ── Nationality Abbreviations ───────────────────────────────────────────

const NATIONALITY_MAP: Record<string, string> = {
  Argentina: 'ARG',
  Australia: 'AUS',
  Austria: 'AUT',
  Belgium: 'BEL',
  'Bosnia-Herzegovina': 'BIH',
  Brazil: 'BRA',
  Cameroon: 'CMR',
  Canada: 'CAN',
  'Central African Republic': 'CAF',
  Chile: 'CHI',
  Colombia: 'COL',
  'Costa Rica': 'CRC',
  "Cote d'Ivoire": 'CIV',
  Croatia: 'CRO',
  'Czech Republic': 'CZE',
  Denmark: 'DEN',
  'Dominican Republic': 'DOM',
  'DR Congo': 'COD',
  Ecuador: 'ECU',
  Egypt: 'EGY',
  England: 'ENG',
  'Equatorial Guinea': 'EQG',
  Finland: 'FIN',
  France: 'FRA',
  'French Guiana': 'GUF',
  Gabon: 'GAB',
  Gambia: 'GAM',
  Georgia: 'GEO',
  Germany: 'GER',
  Ghana: 'GHA',
  Greece: 'GRE',
  Guinea: 'GUI',
  'Guinea-Bissau': 'GNB',
  Honduras: 'HON',
  Hungary: 'HUN',
  Iceland: 'ISL',
  Iran: 'IRN',
  Iraq: 'IRQ',
  Ireland: 'IRL',
  Israel: 'ISR',
  Italy: 'ITA',
  Jamaica: 'JAM',
  Japan: 'JPN',
  Kosovo: 'KOS',
  Mali: 'MLI',
  Mexico: 'MEX',
  Montenegro: 'MNE',
  Morocco: 'MAR',
  Netherlands: 'NED',
  'New Zealand': 'NZL',
  Nigeria: 'NGA',
  'North Macedonia': 'MKD',
  'Northern Ireland': 'NIR',
  Norway: 'NOR',
  Panama: 'PAN',
  Paraguay: 'PAR',
  Peru: 'PER',
  Poland: 'POL',
  Portugal: 'POR',
  'Republic of Ireland': 'IRL',
  Romania: 'ROU',
  Russia: 'RUS',
  Scotland: 'SCO',
  Senegal: 'SEN',
  Serbia: 'SRB',
  Slovakia: 'SVK',
  Slovenia: 'SVN',
  'South Africa': 'RSA',
  'South Korea': 'KOR',
  Spain: 'ESP',
  Sweden: 'SWE',
  Switzerland: 'SUI',
  'Trinidad and Tobago': 'TRI',
  Tunisia: 'TUN',
  Turkey: 'TUR',
  Ukraine: 'UKR',
  'United Arab Emirates': 'UAE',
  'United States': 'USA',
  Uruguay: 'URU',
  Venezuela: 'VEN',
  Wales: 'WAL',
  'Antigua and Barbuda': 'ATG',
  'St. Kitts & Nevis': 'SKN',
  Albania: 'ALB',
  Algeria: 'ALG',
  Angola: 'ANG',
  Benin: 'BEN',
  Bolivia: 'BOL',
  Bulgaria: 'BUL',
  'Burkina Faso': 'BFA',
  Burundi: 'BDI',
  'Cape Verde': 'CPV',
  China: 'CHN',
  Comoros: 'COM',
  Congo: 'CGO',
  Cuba: 'CUB',
  Curaçao: 'CUW',
  Cyprus: 'CYP',
  'El Salvador': 'SLV',
  Estonia: 'EST',
  Ethiopia: 'ETH',
  Guadeloupe: 'GPE',
  Guatemala: 'GUA',
  Haiti: 'HAI',
  India: 'IND',
  Indonesia: 'IDN',
  Kenya: 'KEN',
  Latvia: 'LVA',
  Lebanon: 'LBN',
  Lithuania: 'LTU',
  Luxembourg: 'LUX',
  Madagascar: 'MAD',
  Martinique: 'MTQ',
  Mauritania: 'MTN',
  Mozambique: 'MOZ',
  Namibia: 'NAM',
  Niger: 'NIG',
  'North Korea': 'PRK',
  Philippines: 'PHI',
  'Saudi Arabia': 'KSA',
  'Sierra Leone': 'SLE',
  Suriname: 'SUR',
  Syria: 'SYR',
  Tanzania: 'TAN',
  Thailand: 'THA',
  Togo: 'TOG',
  Uganda: 'UGA',
  Uzbekistan: 'UZB',
  Zambia: 'ZAM',
  Zimbabwe: 'ZIM',
};

export function formatNationality(nationality: string): string {
  return NATIONALITY_MAP[nationality] ?? nationality.substring(0, 3).toUpperCase();
}

// ── League Abbreviations ────────────────────────────────────────────────

const LEAGUE_MAP: Record<string, string> = {
  'Premier League': 'PL',
  'La Liga': 'LaLiga',
  Bundesliga: 'BuLi',
  'Serie A': 'Serie A',
  'Ligue 1': 'L1',
  'Primeira Liga': 'Liga PT',
  'Belgian Pro League': 'JPL',
  'Danish Superliga': 'DSL',
  'Russian Premier League': 'RPL',
  'Super League Greece': 'SLG',
};

export function formatLeague(league: string): string {
  return LEAGUE_MAP[league] ?? league;
}
