import * as path from 'path';
import * as fs from 'fs';
import { Player } from '../../types/player';
import { validateGrid } from '../gridValidator';
import { isImpossibleCombination } from '../gridValidator';
import { generateGrid, generateValidGrid } from '../gridGenerator';

const playersPath = path.resolve(__dirname, '../../data/players_db_v1.json');
const players: Player[] = JSON.parse(fs.readFileSync(playersPath, 'utf-8'));

describe('gridValidator', () => {
  describe('validateGrid with real player data', () => {
    it('should validate a grid generated by generateValidGrid', () => {
      const grid = generateValidGrid(players, 12345);
      expect(grid).not.toBeNull();
      if (!grid) return;

      const result = validateGrid(grid, players);
      expect(result.isValid).toBe(true);
      expect(result.invalidCells).toHaveLength(0);
    });

    it('should report invalid cells for a raw grid that may have gaps', () => {
      // Use a raw generateGrid (no retry) which might produce cells with < 5 players
      const grid = generateGrid(players, 99999);
      const result = validateGrid(grid, players);

      // Verify structure regardless of validity
      expect(result.cellResults).toHaveLength(3);
      result.cellResults.forEach((row) => {
        expect(row).toHaveLength(3);
        row.forEach((cell) => {
          expect(cell).toHaveProperty('row');
          expect(cell).toHaveProperty('col');
          expect(cell).toHaveProperty('playerCount');
          expect(cell).toHaveProperty('isValid');
          expect(typeof cell.playerCount).toBe('number');
          expect(cell.playerCount).toBeGreaterThanOrEqual(0);
        });
      });
    });

    it('should validate 100 random grids generated by generateValidGrid', () => {
      for (let i = 0; i < 100; i++) {
        const grid = generateValidGrid(players, i * 1000);
        expect(grid).not.toBeNull();
        if (!grid) continue;

        const result = validateGrid(grid, players);
        expect(result.isValid).toBe(true);

        // Every cell must have >= 5 valid players
        result.cellResults.forEach((row) => {
          row.forEach((cell) => {
            expect(cell.playerCount).toBeGreaterThanOrEqual(5);
          });
        });
      }
    }, 30000);
  });

  describe('isImpossibleCombination', () => {
    it('should flag same type with different values as impossible', () => {
      expect(
        isImpossibleCombination(
          { type: 'league', value: 'Serie A' },
          { type: 'league', value: 'La Liga' },
        ),
      ).toBe(true);
    });

    it('should NOT flag same type with same value', () => {
      expect(
        isImpossibleCombination(
          { type: 'league', value: 'Serie A' },
          { type: 'league', value: 'Serie A' },
        ),
      ).toBe(false);
    });

    it('should NOT flag different types', () => {
      expect(
        isImpossibleCombination(
          { type: 'league', value: 'Serie A' },
          { type: 'nationality', value: 'Italy' },
        ),
      ).toBe(false);
    });

    it('should flag two different teams as impossible', () => {
      expect(
        isImpossibleCombination(
          { type: 'current_team', value: 'Inter Milan' },
          { type: 'current_team', value: 'AS Roma' },
        ),
      ).toBe(true);
    });

    it('should flag two different positions as impossible', () => {
      expect(
        isImpossibleCombination(
          { type: 'position', value: 'Attack' },
          { type: 'position', value: 'Goalkeeper' },
        ),
      ).toBe(true);
    });
  });
});
