#!/usr/bin/env python3
"""Generate expanded matches_db.json with 200+ matches."""
import json

z = [0]*11  # placeholder IDs

matches = [
    # ============ 1990s ============
    {"match_id":"wc-final-1990","date":"1990-07-08","competition":"FIFA World Cup Final","season":"1990",
     "opponent_a":"West Germany","opponent_b":"Argentina","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Bodo Illgner","Thomas Berthold","Guido Buchwald","Klaus Augenthaler","Andreas Brehme","Lothar Matthaus","Thomas Hassler","Pierre Littbarski","Rudi Voller","Jurgen Klinsmann","Olaf Thon"],
     "lineup_b_names":["Sergio Goycochea","Roberto Sensini","Oscar Ruggeri","Juan Simon","Nestor Lorenzo","Pedro Monzon","Jose Basualdo","Jose Serrizuela","Gustavo Dezotti","Diego Maradona","Jorge Burruchaga"]},
    {"match_id":"euro-final-1992","date":"1992-06-26","competition":"UEFA European Championship Final","season":"1992",
     "opponent_a":"Denmark","opponent_b":"Germany","score":"2-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Peter Schmeichel","John Sivebaek","Lars Olsen","Kent Nielsen","Henrik Andersen","Kim Vilfort","John Jensen","Kim Christofte","Brian Laudrup","Flemming Povlsen","Henrik Larsen"],
     "lineup_b_names":["Bodo Illgner","Stefan Reuter","Jurgen Kohler","Guido Buchwald","Andreas Brehme","Thomas Hassler","Stefan Effenberg","Thomas Helmer","Karl-Heinz Riedle","Jurgen Klinsmann","Matthias Sammer"]},
    {"match_id":"wc-final-1994","date":"1994-07-17","competition":"FIFA World Cup Final","season":"1994",
     "opponent_a":"Brazil","opponent_b":"Italy","score":"0-0 (3-2 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Taffarel","Jorginho","Aldair","Marcio Santos","Branco","Mazinho","Mauro Silva","Zinho","Dunga","Romario","Bebeto"],
     "lineup_b_names":["Gianluca Pagliuca","Roberto Mussi","Franco Baresi","Alessandro Costacurta","Antonio Benarrivo","Demetrio Albertini","Dino Baggio","Nicola Berti","Roberto Donadoni","Roberto Baggio","Daniele Massaro"]},
    {"match_id":"ucl-final-1994","date":"1994-05-18","competition":"UEFA Champions League Final","season":"1993-94",
     "opponent_a":"AC Milan","opponent_b":"Barcelona","score":"4-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Sebastiano Rossi","Mauro Tassotti","Franco Baresi","Alessandro Costacurta","Paolo Maldini","Demetrio Albertini","Marcel Desailly","Zvonimir Boban","Dejan Savicevic","Daniele Massaro","Roberto Donadoni"],
     "lineup_b_names":["Andoni Zubizarreta","Albert Ferrer","Miguel Angel Nadal","Ronald Koeman","Sergi Barjuan","Pep Guardiola","Bakero","Guillermo Amor","Hristo Stoichkov","Romario","Txiki Begiristain"]},
    {"match_id":"ucl-final-1999","date":"1999-05-26","competition":"UEFA Champions League Final","season":"1998-99",
     "opponent_a":"Manchester United","opponent_b":"Bayern Munich","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Peter Schmeichel","Gary Neville","Ronny Johnsen","Jaap Stam","Denis Irwin","David Beckham","Nicky Butt","Ryan Giggs","Jesper Blomqvist","Andy Cole","Dwight Yorke"],
     "lineup_b_names":["Oliver Kahn","Markus Babbel","Thomas Linke","Samuel Kuffour","Michael Tarnat","Jens Jeremies","Stefan Effenberg","Lothar Matthaus","Mario Basler","Alexander Zickler","Carsten Jancker"]},
    {"match_id":"wc-final-1998","date":"1998-07-12","competition":"FIFA World Cup Final","season":"1998",
     "opponent_a":"France","opponent_b":"Brazil","score":"3-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Fabien Barthez","Lilian Thuram","Marcel Desailly","Laurent Blanc","Bixente Lizarazu","Didier Deschamps","Emmanuel Petit","Christian Karembeu","Youri Djorkaeff","Zinedine Zidane","Stephane Guivarch"],
     "lineup_b_names":["Taffarel","Cafu","Aldair","Junior Baiano","Roberto Carlos","Cesar Sampaio","Dunga","Rivaldo","Leonardo","Ronaldo","Bebeto"]},
    {"match_id":"wc-sf-1998-france-croatia","date":"1998-07-08","competition":"FIFA World Cup Semi-Final","season":"1998",
     "opponent_a":"France","opponent_b":"Croatia","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Fabien Barthez","Lilian Thuram","Laurent Blanc","Marcel Desailly","Bixente Lizarazu","Didier Deschamps","Christian Karembeu","Emmanuel Petit","Youri Djorkaeff","Zinedine Zidane","Stephane Guivarch"],
     "lineup_b_names":["Drazen Ladic","Igor Stimac","Slaven Bilic","Robert Jarni","Mario Stanic","Zvonimir Boban","Robert Prosinecki","Aljosa Asanovic","Mario Stanic","Davor Suker","Goran Vlaovic"]},
    {"match_id":"epl-1999-manu-arsenal","date":"1999-02-14","competition":"Premier League","season":"1998-99",
     "opponent_a":"Manchester United","opponent_b":"Arsenal","score":"1-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Peter Schmeichel","Gary Neville","Denis Irwin","Jaap Stam","Ronny Johnsen","David Beckham","Roy Keane","Paul Scholes","Ryan Giggs","Andy Cole","Dwight Yorke"],
     "lineup_b_names":["David Seaman","Lee Dixon","Nigel Winterburn","Tony Adams","Martin Keown","Patrick Vieira","Emmanuel Petit","Ray Parlour","Marc Overmars","Dennis Bergkamp","Nicolas Anelka"]},
    # ============ 2000s ============
    {"match_id":"ucl-final-2000","date":"2000-05-24","competition":"UEFA Champions League Final","season":"1999-00",
     "opponent_a":"Real Madrid","opponent_b":"Valencia","score":"3-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Iker Casillas","Michel Salgado","Fernando Hierro","Ivan Helguera","Roberto Carlos","Steve McManaman","Fernando Redondo","Claude Makelele","Raul","Morientes","Nicolas Anelka"],
     "lineup_b_names":["Santiago Canizares","Jocelyn Angloma","Amedeo Carboni","Miroslav Djukic","Gerardo","Miguel Angel Angulo","Mendieta","Baraja","Kily Gonzalez","Claudio Lopez","Gerard Lopez"]},
    {"match_id":"euro-final-2000","date":"2000-07-02","competition":"UEFA European Championship Final","season":"2000",
     "opponent_a":"France","opponent_b":"Italy","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Fabien Barthez","Lilian Thuram","Marcel Desailly","Laurent Blanc","Bixente Lizarazu","Didier Deschamps","Patrick Vieira","Emmanuel Petit","Youri Djorkaeff","Zinedine Zidane","Christophe Dugarry"],
     "lineup_b_names":["Francesco Toldo","Gianluca Zambrotta","Fabio Cannavaro","Alessandro Nesta","Paolo Maldini","Luigi Di Biagio","Demetrio Albertini","Stefano Fiore","Francesco Totti","Marco Delvecchio","Gianluca Pessotto"]},
    {"match_id":"ucl-final-2002","date":"2002-05-15","competition":"UEFA Champions League Final","season":"2001-02",
     "opponent_a":"Real Madrid","opponent_b":"Bayer Leverkusen","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Cesar","Michel Salgado","Fernando Hierro","Roberto Carlos","Helguera","Makelele","Steve McManaman","Zinedine Zidane","Figo","Raul","Morientes"],
     "lineup_b_names":["Hans-Jorg Butt","Zoltan Sebescen","Lucio","Boris Zivkovic","Diego Placente","Carsten Ramelow","Michael Ballack","Bernd Schneider","Yildiray Basturk","Thomas Brdaric","Oliver Neuville"]},
    {"match_id":"wc-final-2002","date":"2002-06-30","competition":"FIFA World Cup Final","season":"2002",
     "opponent_a":"Brazil","opponent_b":"Germany","score":"2-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Marcos","Lucio","Roque Junior","Edmilson","Cafu","Gilberto Silva","Kleberson","Roberto Carlos","Ronaldinho","Rivaldo","Ronaldo"],
     "lineup_b_names":["Oliver Kahn","Thomas Linke","Carsten Ramelow","Christoph Metzelder","Dietmar Hamann","Bernd Schneider","Marco Bode","Torsten Frings","Miroslav Klose","Oliver Neuville","Jens Jeremies"]},
    {"match_id":"ucl-final-2003","date":"2003-05-28","competition":"UEFA Champions League Final","season":"2002-03",
     "opponent_a":"AC Milan","opponent_b":"Juventus","score":"0-0 (3-2 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Dida","Cafu","Paolo Maldini","Alessandro Nesta","Alessandro Costacurta","Gennaro Gattuso","Andrea Pirlo","Clarence Seedorf","Rui Costa","Filippo Inzaghi","Andriy Shevchenko"],
     "lineup_b_names":["Gianluigi Buffon","Lilian Thuram","Ciro Ferrara","Igor Tudor","Gianluca Zambrotta","Pavel Nedved","Edgar Davids","Mauro Camoranesi","Antonio Conte","Alessandro Del Piero","David Trezeguet"]},
    {"match_id":"ucl-final-2004","date":"2004-05-26","competition":"UEFA Champions League Final","season":"2003-04",
     "opponent_a":"Porto","opponent_b":"Monaco","score":"3-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Vitor Baia","Paulo Ferreira","Jorge Costa","Ricardo Carvalho","Nuno Valente","Costinha","Maniche","Deco","Pedro Mendes","Carlos Alberto","Derlei"],
     "lineup_b_names":["Flavio Roma","Hugo Ibarra","Gael Givet","Julien Rodriguez","Patrice Evra","Edouard Cisse","Akis Zikos","Lucas Bernardi","Ludovic Giuly","Dado Prso","Shabani Nonda"]},
    {"match_id":"euro-final-2004","date":"2004-07-04","competition":"UEFA European Championship Final","season":"2004",
     "opponent_a":"Greece","opponent_b":"Portugal","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Antonios Nikopolidis","Giourkas Seitaridis","Traianos Dellas","Mihalis Kapsis","Takis Fyssas","Kostas Katsouranis","Theodoros Zagorakis","Angelos Basinas","Angelos Charisteas","Stelios Giannakopoulos","Giorgos Karagounis"],
     "lineup_b_names":["Ricardo","Miguel","Ricardo Carvalho","Jorge Andrade","Nuno Valente","Costinha","Maniche","Deco","Luis Figo","Cristiano Ronaldo","Pauleta"]},
    # UCL + WC 2005-2006 already in existing file, start from gap
    {"match_id":"ucl-sf-2005-chelsea-liverpool","date":"2005-05-03","competition":"UEFA Champions League Semi-Final","season":"2004-05",
     "opponent_a":"Liverpool","opponent_b":"Chelsea","score":"1-0 (agg 1-0)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Jerzy Dudek","Steve Finnan","Jamie Carragher","Sami Hyypia","Djimi Traore","Steven Gerrard","Xabi Alonso","Dietmar Hamann","Luis Garcia","Milan Baros","John Arne Riise"],
     "lineup_b_names":["Petr Cech","Paulo Ferreira","Ricardo Carvalho","John Terry","William Gallas","Claude Makelele","Frank Lampard","Tiago","Joe Cole","Eidur Gudjohnsen","Damien Duff"]},
    {"match_id":"ucl-final-2005","date":"2005-05-25","competition":"UEFA Champions League Final","season":"2004-05",
     "opponent_a":"Liverpool","opponent_b":"AC Milan","score":"3-3 (3-2 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Jerzy Dudek","Steve Finnan","Jamie Carragher","Sami Hyypia","Djimi Traore","Steven Gerrard","Xabi Alonso","Dietmar Hamann","John Arne Riise","Harry Kewell","Milan Baros"],
     "lineup_b_names":["Dida","Cafu","Jaap Stam","Alessandro Nesta","Paolo Maldini","Gennaro Gattuso","Andrea Pirlo","Clarence Seedorf","Kaka","Andriy Shevchenko","Hernan Crespo"]},
    {"match_id":"ucl-final-2006","date":"2006-05-17","competition":"UEFA Champions League Final","season":"2005-06",
     "opponent_a":"Barcelona","opponent_b":"Arsenal","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Victor Valdes","Oleguer","Carles Puyol","Rafael Marquez","Giovanni van Bronckhorst","Mark van Bommel","Edmilson","Deco","Ludovic Giuly","Ronaldinho","Samuel Eto'o"],
     "lineup_b_names":["Jens Lehmann","Emmanuel Eboue","Kolo Toure","Sol Campbell","Ashley Cole","Cesc Fabregas","Gilberto Silva","Alexander Hleb","Robert Pires","Thierry Henry","Fredrik Ljungberg"]},
    {"match_id":"wc-sf-2006-germany-italy","date":"2006-07-04","competition":"FIFA World Cup Semi-Final","season":"2006",
     "opponent_a":"Germany","opponent_b":"Italy","score":"0-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Jens Lehmann","Philipp Lahm","Christoph Metzelder","Per Mertesacker","Arne Friedrich","Bernd Schneider","Michael Ballack","Torsten Frings","Tim Borowski","Miroslav Klose","Lukas Podolski"],
     "lineup_b_names":["Gianluigi Buffon","Fabio Grosso","Fabio Cannavaro","Marco Materazzi","Gianluca Zambrotta","Gennaro Gattuso","Andrea Pirlo","Simone Perrotta","Mauro Camoranesi","Francesco Totti","Luca Toni"]},
    {"match_id":"wc-final-2006","date":"2006-07-09","competition":"FIFA World Cup Final","season":"2006",
     "opponent_a":"Italy","opponent_b":"France","score":"1-1 (5-3 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Gianluigi Buffon","Fabio Grosso","Fabio Cannavaro","Marco Materazzi","Gianluca Zambrotta","Gennaro Gattuso","Andrea Pirlo","Simone Perrotta","Mauro Camoranesi","Francesco Totti","Luca Toni"],
     "lineup_b_names":["Fabien Barthez","Willy Sagnol","Lilian Thuram","William Gallas","Eric Abidal","Claude Makelele","Patrick Vieira","Franck Ribery","Zinedine Zidane","Florent Malouda","Thierry Henry"]},
    {"match_id":"ucl-final-2007","date":"2007-05-23","competition":"UEFA Champions League Final","season":"2006-07",
     "opponent_a":"AC Milan","opponent_b":"Liverpool","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Dida","Massimo Oddo","Alessandro Nesta","Paolo Maldini","Marek Jankulovski","Gennaro Gattuso","Andrea Pirlo","Massimo Ambrosini","Clarence Seedorf","Kaka","Filippo Inzaghi"],
     "lineup_b_names":["Pepe Reina","Steve Finnan","Jamie Carragher","Daniel Agger","John Arne Riise","Steven Gerrard","Xabi Alonso","Javier Mascherano","Boudewijn Zenden","Dirk Kuyt","Craig Bellamy"]},
    {"match_id":"ucl-final-2008","date":"2008-05-21","competition":"UEFA Champions League Final","season":"2007-08",
     "opponent_a":"Manchester United","opponent_b":"Chelsea","score":"1-1 (6-5 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Edwin van der Sar","Wes Brown","Rio Ferdinand","Nemanja Vidic","Patrice Evra","Owen Hargreaves","Michael Carrick","Paul Scholes","Cristiano Ronaldo","Wayne Rooney","Carlos Tevez"],
     "lineup_b_names":["Petr Cech","Michael Essien","Ricardo Carvalho","John Terry","Ashley Cole","Claude Makelele","Frank Lampard","Michael Ballack","Joe Cole","Florent Malouda","Didier Drogba"]},
    {"match_id":"ucl-final-2009","date":"2009-05-27","competition":"UEFA Champions League Final","season":"2008-09",
     "opponent_a":"Barcelona","opponent_b":"Manchester United","score":"2-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Victor Valdes","Dani Alves","Gerard Pique","Carles Puyol","Sylvinho","Xavi","Sergio Busquets","Andres Iniesta","Lionel Messi","Samuel Eto'o","Thierry Henry"],
     "lineup_b_names":["Edwin van der Sar","John O'Shea","Rio Ferdinand","Nemanja Vidic","Patrice Evra","Cristiano Ronaldo","Michael Carrick","Anderson","Park Ji-sung","Wayne Rooney","Carlos Tevez"]},
    # ============ 2010s ============
    {"match_id":"ucl-final-2010","date":"2010-05-22","competition":"UEFA Champions League Final","season":"2009-10",
     "opponent_a":"Inter Milan","opponent_b":"Bayern Munich","score":"2-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Julio Cesar","Maicon","Lucio","Walter Samuel","Javier Zanetti","Esteban Cambiasso","Wesley Sneijder","Dejan Stankovic","Goran Pandev","Samuel Eto'o","Diego Milito"],
     "lineup_b_names":["Hans-Jorg Butt","Philipp Lahm","Martin Demichelis","Daniel Van Buyten","Holger Badstuber","Hamit Altintop","Mark van Bommel","Bastian Schweinsteiger","Arjen Robben","Thomas Muller","Ivica Olic"]},
    {"match_id":"wc-final-2010","date":"2010-07-11","competition":"FIFA World Cup Final","season":"2010",
     "opponent_a":"Spain","opponent_b":"Netherlands","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Iker Casillas","Sergio Ramos","Gerard Pique","Carles Puyol","Joan Capdevila","Xavi","Sergio Busquets","Xabi Alonso","Andres Iniesta","David Villa","Pedro Rodriguez"],
     "lineup_b_names":["Maarten Stekelenburg","Gregory van der Wiel","John Heitinga","Joris Mathijsen","Giovanni van Bronckhorst","Mark van Bommel","Nigel de Jong","Wesley Sneijder","Arjen Robben","Robin van Persie","Dirk Kuyt"]},
    {"match_id":"ucl-final-2011","date":"2011-05-28","competition":"UEFA Champions League Final","season":"2010-11",
     "opponent_a":"Barcelona","opponent_b":"Manchester United","score":"3-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Victor Valdes","Dani Alves","Gerard Pique","Javier Mascherano","Eric Abidal","Sergio Busquets","Xavi","Andres Iniesta","Lionel Messi","David Villa","Pedro Rodriguez"],
     "lineup_b_names":["Edwin van der Sar","Fabio","Rio Ferdinand","Nemanja Vidic","Patrice Evra","Antonio Valencia","Michael Carrick","Park Ji-sung","Ryan Giggs","Wayne Rooney","Javier Hernandez"]},
    {"match_id":"euro-final-2012","date":"2012-07-01","competition":"UEFA European Championship Final","season":"2012",
     "opponent_a":"Spain","opponent_b":"Italy","score":"4-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Iker Casillas","Alvaro Arbeloa","Sergio Ramos","Gerard Pique","Jordi Alba","Xavi","Sergio Busquets","Xabi Alonso","Andres Iniesta","Cesc Fabregas","David Silva"],
     "lineup_b_names":["Gianluigi Buffon","Ignazio Abate","Andrea Barzagli","Leonardo Bonucci","Giorgio Chiellini","Claudio Marchisio","Andrea Pirlo","Daniele De Rossi","Antonio Cassano","Mario Balotelli","Thiago Motta"]},
    {"match_id":"ucl-final-2012","date":"2012-05-19","competition":"UEFA Champions League Final","season":"2011-12",
     "opponent_a":"Bayern Munich","opponent_b":"Chelsea","score":"1-1 (3-4 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Philipp Lahm","Jerome Boateng","Anatoliy Tymoshchuk","Diego Contento","Arjen Robben","Bastian Schweinsteiger","Toni Kroos","Franck Ribery","Thomas Muller","Mario Gomez"],
     "lineup_b_names":["Petr Cech","Jose Bosingwa","Gary Cahill","David Luiz","Ashley Cole","Salomon Kalou","John Obi Mikel","Frank Lampard","Juan Mata","Ryan Bertrand","Didier Drogba"]},
    {"match_id":"ucl-final-2013","date":"2013-05-25","competition":"UEFA Champions League Final","season":"2012-13",
     "opponent_a":"Bayern Munich","opponent_b":"Borussia Dortmund","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Philipp Lahm","Jerome Boateng","Dante","David Alaba","Arjen Robben","Bastian Schweinsteiger","Javi Martinez","Franck Ribery","Thomas Muller","Mario Mandzukic"],
     "lineup_b_names":["Roman Weidenfeller","Lukasz Piszczek","Neven Subotic","Mats Hummels","Marcel Schmelzer","Sven Bender","Ilkay Gundogan","Jakub Blaszczykowski","Mario Gotze","Marco Reus","Robert Lewandowski"]},
    {"match_id":"ucl-final-2014","date":"2014-05-24","competition":"UEFA Champions League Final","season":"2013-14",
     "opponent_a":"Real Madrid","opponent_b":"Atletico Madrid","score":"4-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Iker Casillas","Dani Carvajal","Sergio Ramos","Pepe","Fabio Coentrao","Luka Modric","Xabi Alonso","Angel Di Maria","Gareth Bale","Karim Benzema","Cristiano Ronaldo"],
     "lineup_b_names":["Thibaut Courtois","Juanfran","Miranda","Diego Godin","Filipe Luis","Gabi","Tiago","Koke","Raul Garcia","Adrian Lopez","Diego Costa"]},
    {"match_id":"wc-sf-2014-brazil-germany","date":"2014-07-08","competition":"FIFA World Cup Semi-Final","season":"2014",
     "opponent_a":"Brazil","opponent_b":"Germany","score":"1-7",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Julio Cesar","Maicon","David Luiz","Dante","Marcelo","Fernandinho","Luiz Gustavo","Oscar","Hulk","Fred","Bernard"],
     "lineup_b_names":["Manuel Neuer","Philipp Lahm","Mats Hummels","Jerome Boateng","Benedikt Howedes","Bastian Schweinsteiger","Sami Khedira","Toni Kroos","Mesut Ozil","Thomas Muller","Miroslav Klose"]},
    {"match_id":"wc-final-2014","date":"2014-07-13","competition":"FIFA World Cup Final","season":"2014",
     "opponent_a":"Germany","opponent_b":"Argentina","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Philipp Lahm","Mats Hummels","Jerome Boateng","Benedikt Howedes","Bastian Schweinsteiger","Sami Khedira","Toni Kroos","Mesut Ozil","Thomas Muller","Miroslav Klose"],
     "lineup_b_names":["Sergio Romero","Pablo Zabaleta","Ezequiel Garay","Martin Demichelis","Marcos Rojo","Javier Mascherano","Lucas Biglia","Enzo Perez","Lionel Messi","Gonzalo Higuain","Ezequiel Lavezzi"]},
    {"match_id":"ucl-final-2015","date":"2015-06-06","competition":"UEFA Champions League Final","season":"2014-15",
     "opponent_a":"Barcelona","opponent_b":"Juventus","score":"3-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Marc-Andre ter Stegen","Dani Alves","Gerard Pique","Javier Mascherano","Jordi Alba","Ivan Rakitic","Sergio Busquets","Andres Iniesta","Lionel Messi","Luis Suarez","Neymar"],
     "lineup_b_names":["Gianluigi Buffon","Stephan Lichtsteiner","Leonardo Bonucci","Giorgio Chiellini","Patrice Evra","Arturo Vidal","Andrea Pirlo","Claudio Marchisio","Paul Pogba","Carlos Tevez","Alvaro Morata"]},
    {"match_id":"ucl-final-2016","date":"2016-05-28","competition":"UEFA Champions League Final","season":"2015-16",
     "opponent_a":"Real Madrid","opponent_b":"Atletico Madrid","score":"1-1 (5-3 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Keylor Navas","Dani Carvajal","Sergio Ramos","Pepe","Marcelo","Luka Modric","Toni Kroos","Casemiro","Gareth Bale","Karim Benzema","Cristiano Ronaldo"],
     "lineup_b_names":["Jan Oblak","Juanfran","Diego Godin","Jose Gimenez","Filipe Luis","Gabi","Koke","Saul Niguez","Augusto Fernandez","Antoine Griezmann","Fernando Torres"]},
    {"match_id":"euro-final-2016","date":"2016-07-10","competition":"UEFA European Championship Final","season":"2016",
     "opponent_a":"Portugal","opponent_b":"France","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Rui Patricio","Cedric Soares","Pepe","Jose Fonte","Raphael Guerreiro","William Carvalho","Adrien Silva","Joao Mario","Nani","Cristiano Ronaldo","Renato Sanches"],
     "lineup_b_names":["Hugo Lloris","Bacary Sagna","Samuel Umtiti","Laurent Koscielny","Patrice Evra","Blaise Matuidi","N'Golo Kante","Paul Pogba","Moussa Sissoko","Antoine Griezmann","Olivier Giroud"]},
    {"match_id":"ucl-final-2017","date":"2017-06-03","competition":"UEFA Champions League Final","season":"2016-17",
     "opponent_a":"Real Madrid","opponent_b":"Juventus","score":"4-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Keylor Navas","Dani Carvajal","Sergio Ramos","Raphael Varane","Marcelo","Luka Modric","Toni Kroos","Casemiro","Isco","Karim Benzema","Cristiano Ronaldo"],
     "lineup_b_names":["Gianluigi Buffon","Dani Alves","Leonardo Bonucci","Giorgio Chiellini","Alex Sandro","Sami Khedira","Miralem Pjanic","Mario Mandzukic","Juan Cuadrado","Paulo Dybala","Gonzalo Higuain"]},
    {"match_id":"ucl-final-2018","date":"2018-05-26","competition":"UEFA Champions League Final","season":"2017-18",
     "opponent_a":"Real Madrid","opponent_b":"Liverpool","score":"3-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Keylor Navas","Dani Carvajal","Sergio Ramos","Raphael Varane","Marcelo","Luka Modric","Toni Kroos","Casemiro","Isco","Karim Benzema","Cristiano Ronaldo"],
     "lineup_b_names":["Loris Karius","Trent Alexander-Arnold","Dejan Lovren","Virgil van Dijk","Andrew Robertson","James Milner","Jordan Henderson","Georginio Wijnaldum","Mohamed Salah","Roberto Firmino","Sadio Mane"]},
    {"match_id":"wc-final-2018","date":"2018-07-15","competition":"FIFA World Cup Final","season":"2018",
     "opponent_a":"France","opponent_b":"Croatia","score":"4-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Hugo Lloris","Benjamin Pavard","Raphael Varane","Samuel Umtiti","Lucas Hernandez","N'Golo Kante","Paul Pogba","Blaise Matuidi","Kylian Mbappe","Antoine Griezmann","Olivier Giroud"],
     "lineup_b_names":["Danijel Subasic","Sime Vrsaljko","Domagoj Vida","Dejan Lovren","Ivan Strinic","Luka Modric","Ivan Rakitic","Marcelo Brozovic","Ivan Perisic","Mario Mandzukic","Ante Rebic"]},
    {"match_id":"wc-r16-2018-france-argentina","date":"2018-06-30","competition":"FIFA World Cup Round of 16","season":"2018",
     "opponent_a":"France","opponent_b":"Argentina","score":"4-3",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Hugo Lloris","Benjamin Pavard","Raphael Varane","Samuel Umtiti","Lucas Hernandez","N'Golo Kante","Paul Pogba","Blaise Matuidi","Kylian Mbappe","Antoine Griezmann","Olivier Giroud"],
     "lineup_b_names":["Franco Armani","Gabriel Mercado","Nicolas Otamendi","Marcos Rojo","Nicolas Tagliafico","Javier Mascherano","Ever Banega","Enzo Perez","Angel Di Maria","Lionel Messi","Gonzalo Higuain"]},
    {"match_id":"ucl-sf-2019-liv-barca","date":"2019-05-07","competition":"UEFA Champions League Semi-Final","season":"2018-19",
     "opponent_a":"Liverpool","opponent_b":"Barcelona","score":"4-0 (agg 4-3)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Alisson","Trent Alexander-Arnold","Joel Matip","Virgil van Dijk","Andrew Robertson","Fabinho","Georginio Wijnaldum","James Milner","Xherdan Shaqiri","Divock Origi","Sadio Mane"],
     "lineup_b_names":["Marc-Andre ter Stegen","Sergi Roberto","Gerard Pique","Clement Lenglet","Jordi Alba","Ivan Rakitic","Sergio Busquets","Arturo Vidal","Lionel Messi","Philippe Coutinho","Luis Suarez"]},
    {"match_id":"ucl-final-2019","date":"2019-06-01","competition":"UEFA Champions League Final","season":"2018-19",
     "opponent_a":"Liverpool","opponent_b":"Tottenham Hotspur","score":"2-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Alisson","Trent Alexander-Arnold","Joel Matip","Virgil van Dijk","Andrew Robertson","Fabinho","Jordan Henderson","Georginio Wijnaldum","Mohamed Salah","Roberto Firmino","Sadio Mane"],
     "lineup_b_names":["Hugo Lloris","Kieran Trippier","Toby Alderweireld","Jan Vertonghen","Danny Rose","Moussa Sissoko","Harry Winks","Dele Alli","Christian Eriksen","Son Heung-min","Harry Kane"]},
    {"match_id":"ucl-final-2020","date":"2020-08-23","competition":"UEFA Champions League Final","season":"2019-20",
     "opponent_a":"Bayern Munich","opponent_b":"Paris Saint-Germain","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Joshua Kimmich","Jerome Boateng","David Alaba","Alphonso Davies","Leon Goretzka","Thiago Alcantara","Serge Gnabry","Thomas Muller","Ivan Perisic","Robert Lewandowski"],
     "lineup_b_names":["Keylor Navas","Thilo Kehrer","Thiago Silva","Presnel Kimpembe","Juan Bernat","Marquinhos","Ander Herrera","Leandro Paredes","Angel Di Maria","Neymar","Kylian Mbappe"]},
    # ============ 2020s ============
    {"match_id":"euro-final-2020","date":"2021-07-11","competition":"UEFA European Championship Final","season":"2020",
     "opponent_a":"Italy","opponent_b":"England","score":"1-1 (3-2 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Gianluigi Donnarumma","Giovanni Di Lorenzo","Leonardo Bonucci","Giorgio Chiellini","Emerson Palmieri","Nicolo Barella","Jorginho","Marco Verratti","Federico Chiesa","Ciro Immobile","Lorenzo Insigne"],
     "lineup_b_names":["Jordan Pickford","Kyle Walker","John Stones","Harry Maguire","Luke Shaw","Declan Rice","Kalvin Phillips","Mason Mount","Bukayo Saka","Harry Kane","Raheem Sterling"]},
    {"match_id":"ucl-final-2021","date":"2021-05-29","competition":"UEFA Champions League Final","season":"2020-21",
     "opponent_a":"Manchester City","opponent_b":"Chelsea","score":"0-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Ederson","Kyle Walker","John Stones","Ruben Dias","Oleksandr Zinchenko","Ilkay Gundogan","Bernardo Silva","Riyad Mahrez","Kevin De Bruyne","Phil Foden","Raheem Sterling"],
     "lineup_b_names":["Edouard Mendy","Cesar Azpilicueta","Thiago Silva","Antonio Rudiger","Reece James","N'Golo Kante","Jorginho","Mason Mount","Kai Havertz","Timo Werner","Ben Chilwell"]},
    {"match_id":"ucl-final-2022","date":"2022-05-28","competition":"UEFA Champions League Final","season":"2021-22",
     "opponent_a":"Liverpool","opponent_b":"Real Madrid","score":"0-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Alisson","Trent Alexander-Arnold","Ibrahima Konate","Virgil van Dijk","Andrew Robertson","Fabinho","Thiago Alcantara","Jordan Henderson","Mohamed Salah","Sadio Mane","Luis Diaz"],
     "lineup_b_names":["Thibaut Courtois","Dani Carvajal","Eder Militao","David Alaba","Ferland Mendy","Luka Modric","Toni Kroos","Casemiro","Federico Valverde","Karim Benzema","Vinicius Junior"]},
    {"match_id":"wc-final-2022","date":"2022-12-18","competition":"FIFA World Cup Final","season":"2022",
     "opponent_a":"Argentina","opponent_b":"France","score":"3-3 (4-2 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Emiliano Martinez","Nahuel Molina","Cristian Romero","Nicolas Otamendi","Nicolas Tagliafico","Rodrigo De Paul","Enzo Fernandez","Alexis Mac Allister","Angel Di Maria","Lionel Messi","Julian Alvarez"],
     "lineup_b_names":["Hugo Lloris","Jules Kounde","Raphael Varane","Dayot Upamecano","Theo Hernandez","Aurelien Tchouameni","Adrien Rabiot","Ousmane Dembele","Antoine Griezmann","Kylian Mbappe","Olivier Giroud"]},
    {"match_id":"wc-sf-2022-argentina-croatia","date":"2022-12-13","competition":"FIFA World Cup Semi-Final","season":"2022",
     "opponent_a":"Argentina","opponent_b":"Croatia","score":"3-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Emiliano Martinez","Nahuel Molina","Cristian Romero","Nicolas Otamendi","Nicolas Tagliafico","Rodrigo De Paul","Enzo Fernandez","Alexis Mac Allister","Angel Di Maria","Lionel Messi","Julian Alvarez"],
     "lineup_b_names":["Dominik Livakovic","Josip Juranovic","Dejan Lovren","Josko Gvardiol","Borna Sosa","Luka Modric","Marcelo Brozovic","Mateo Kovacic","Mario Pasalic","Ivan Perisic","Bruno Petkovic"]},
    {"match_id":"wc-sf-2022-france-morocco","date":"2022-12-14","competition":"FIFA World Cup Semi-Final","season":"2022",
     "opponent_a":"France","opponent_b":"Morocco","score":"2-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Hugo Lloris","Jules Kounde","Raphael Varane","Dayot Upamecano","Theo Hernandez","Aurelien Tchouameni","Adrien Rabiot","Ousmane Dembele","Antoine Griezmann","Kylian Mbappe","Olivier Giroud"],
     "lineup_b_names":["Yassine Bounou","Achraf Hakimi","Romain Saiss","Nayef Aguerd","Noussair Mazraoui","Sofyan Amrabat","Azzedine Ounahi","Selim Amallah","Hakim Ziyech","Youssef En-Nesyri","Sofiane Boufal"]},
    {"match_id":"wc-qf-2022-brazil-croatia","date":"2022-12-09","competition":"FIFA World Cup Quarter-Final","season":"2022",
     "opponent_a":"Brazil","opponent_b":"Croatia","score":"1-1 (2-4 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Alisson","Eder Militao","Thiago Silva","Marquinhos","Danilo","Casemiro","Lucas Paqueta","Raphinha","Neymar","Vinicius Junior","Richarlison"],
     "lineup_b_names":["Dominik Livakovic","Josip Juranovic","Dejan Lovren","Josko Gvardiol","Borna Sosa","Luka Modric","Marcelo Brozovic","Mateo Kovacic","Mario Pasalic","Andrej Kramaric","Ivan Perisic"]},
    {"match_id":"ucl-final-2023","date":"2023-06-10","competition":"UEFA Champions League Final","season":"2022-23",
     "opponent_a":"Manchester City","opponent_b":"Inter Milan","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Ederson","Kyle Walker","Ruben Dias","Manuel Akanji","Nathan Ake","Rodri","Bernardo Silva","John Stones","Kevin De Bruyne","Ilkay Gundogan","Erling Haaland"],
     "lineup_b_names":["Andre Onana","Matteo Darmian","Francesco Acerbi","Alessandro Bastoni","Denzel Dumfries","Nicolo Barella","Hakan Calhanoglu","Henrikh Mkhitaryan","Federico Dimarco","Lautaro Martinez","Edin Dzeko"]},
    {"match_id":"ucl-final-2024","date":"2024-06-01","competition":"UEFA Champions League Final","season":"2023-24",
     "opponent_a":"Borussia Dortmund","opponent_b":"Real Madrid","score":"0-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Gregor Kobel","Julian Ryerson","Mats Hummels","Nico Schlotterbeck","Ian Maatsen","Marcel Sabitzer","Emre Can","Julian Brandt","Jadon Sancho","Niclas Fullkrug","Karim Adeyemi"],
     "lineup_b_names":["Thibaut Courtois","Dani Carvajal","Antonio Rudiger","Nacho Fernandez","Ferland Mendy","Federico Valverde","Toni Kroos","Eduardo Camavinga","Jude Bellingham","Vinicius Junior","Rodrygo"]},
    # Additional classic matches
    {"match_id":"epl-agueroooo-2012","date":"2012-05-13","competition":"Premier League","season":"2011-12",
     "opponent_a":"Manchester City","opponent_b":"Queens Park Rangers","score":"3-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Joe Hart","Pablo Zabaleta","Joleon Lescott","Vincent Kompany","Gael Clichy","Yaya Toure","Gareth Barry","Samir Nasri","David Silva","Carlos Tevez","Sergio Aguero"],
     "lineup_b_names":["Paddy Kenny","Nedum Onuoha","Clint Hill","Anton Ferdinand","Taye Taiwo","Shaun Wright-Phillips","Joey Barton","Shaun Derry","Jamie Mackie","Djibril Cisse","Bobby Zamora"]},
    {"match_id":"clasico-2009-05-02","date":"2009-05-02","competition":"La Liga","season":"2008-09",
     "opponent_a":"Real Madrid","opponent_b":"Barcelona","score":"2-6",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Iker Casillas","Sergio Ramos","Pepe","Fabio Cannavaro","Marcelo","Lassana Diarra","Fernando Gago","Arjen Robben","Wesley Sneijder","Gonzalo Higuain","Raul"],
     "lineup_b_names":["Victor Valdes","Dani Alves","Gerard Pique","Carles Puyol","Eric Abidal","Xavi","Sergio Busquets","Yaya Toure","Andres Iniesta","Lionel Messi","Thierry Henry"]},
    {"match_id":"clasico-2017-04-23","date":"2017-04-23","competition":"La Liga","season":"2016-17",
     "opponent_a":"Real Madrid","opponent_b":"Barcelona","score":"2-3",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Keylor Navas","Dani Carvajal","Sergio Ramos","Raphael Varane","Marcelo","Casemiro","Luka Modric","Toni Kroos","Marco Asensio","Karim Benzema","Cristiano Ronaldo"],
     "lineup_b_names":["Marc-Andre ter Stegen","Sergi Roberto","Gerard Pique","Samuel Umtiti","Jordi Alba","Sergio Busquets","Ivan Rakitic","Andres Iniesta","Lionel Messi","Luis Suarez","Neymar"]},
    {"match_id":"epl-leicester-title-2016","date":"2016-05-01","competition":"Premier League","season":"2015-16",
     "opponent_a":"Manchester United","opponent_b":"Leicester City","score":"1-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["David de Gea","Matteo Darmian","Chris Smalling","Daley Blind","Marcos Rojo","Antonio Valencia","Michael Carrick","Marouane Fellaini","Jesse Lingard","Anthony Martial","Wayne Rooney"],
     "lineup_b_names":["Kasper Schmeichel","Danny Simpson","Wes Morgan","Robert Huth","Christian Fuchs","Riyad Mahrez","N'Golo Kante","Danny Drinkwater","Marc Albrighton","Jamie Vardy","Leonardo Ulloa"]},
    {"match_id":"copa-america-final-2021","date":"2021-07-10","competition":"Copa America Final","season":"2021",
     "opponent_a":"Argentina","opponent_b":"Brazil","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Emiliano Martinez","Nahuel Molina","Cristian Romero","Nicolas Otamendi","Marcos Acuna","Rodrigo De Paul","Leandro Paredes","Giovani Lo Celso","Lionel Messi","Lautaro Martinez","Angel Di Maria"],
     "lineup_b_names":["Ederson","Danilo","Marquinhos","Thiago Silva","Alex Sandro","Fred","Casemiro","Lucas Paqueta","Richarlison","Neymar","Gabriel Jesus"]},
    {"match_id":"copa-america-final-2024","date":"2024-07-14","competition":"Copa America Final","season":"2024",
     "opponent_a":"Argentina","opponent_b":"Colombia","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Emiliano Martinez","Nahuel Molina","Cristian Romero","Lisandro Martinez","Nicolas Tagliafico","Rodrigo De Paul","Enzo Fernandez","Alexis Mac Allister","Angel Di Maria","Lionel Messi","Julian Alvarez"],
     "lineup_b_names":["Camilo Vargas","Santiago Arias","Davinson Sanchez","Carlos Cuesta","Johan Mojica","Jefferson Lerma","Richard Rios","James Rodriguez","Jhon Arias","Jhon Cordoba","Luis Diaz"]},
    {"match_id":"afcon-final-2022","date":"2022-02-06","competition":"Africa Cup of Nations Final","season":"2021",
     "opponent_a":"Senegal","opponent_b":"Egypt","score":"0-0 (4-2 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Edouard Mendy","Bouna Sarr","Kalidou Koulibaly","Abdou Diallo","Saliou Ciss","Nampalys Mendy","Idrissa Gueye","Cheikhou Kouyate","Ismaila Sarr","Sadio Mane","Boulaye Dia"],
     "lineup_b_names":["Mohamed Abou Gabal","Omar Kamal","Mahmoud Hamdy","Ahmed Hegazi","Ayman Ashraf","Amr El Solia","Hamdi Fathi","Mohamed Elneny","Omar Marmoush","Mohamed Salah","Mostafa Mohamed"]},
    {"match_id":"epl-arsenal-tottenham-2004","date":"2004-11-13","competition":"Premier League","season":"2004-05",
     "opponent_a":"Arsenal","opponent_b":"Tottenham Hotspur","score":"5-4",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Almunia","Lauren","Kolo Toure","Sol Campbell","Ashley Cole","Cesc Fabregas","Patrick Vieira","Robert Pires","Freddie Ljungberg","Thierry Henry","Dennis Bergkamp"],
     "lineup_b_names":["Paul Robinson","Stephen Kelly","Noureddine Naybet","Anthony Gardner","Erik Edman","Jermain Defoe","Pedro Mendes","Sean Davis","Robbie Keane","Frederic Kanoute","Reto Ziegler"]},
    {"match_id":"epl-gerrard-final-2006","date":"2006-05-13","competition":"FA Cup Final","season":"2005-06",
     "opponent_a":"Liverpool","opponent_b":"West Ham United","score":"3-3 (3-1 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Pepe Reina","Steve Finnan","Jamie Carragher","Sami Hyypia","John Arne Riise","Steven Gerrard","Xabi Alonso","Didi Hamann","Harry Kewell","Djibril Cisse","Peter Crouch"],
     "lineup_b_names":["Shaka Hislop","Lionel Scaloni","Danny Gabbidon","Anton Ferdinand","Paul Konchesky","Yossi Benayoun","Nigel Reo-Coker","Carl Fletcher","Matthew Etherington","Dean Ashton","Bobby Zamora"]},
    {"match_id":"bundesliga-dortmund-bayern-2013","date":"2013-04-23","competition":"UEFA Champions League Semi-Final","season":"2012-13",
     "opponent_a":"Borussia Dortmund","opponent_b":"Real Madrid","score":"4-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Roman Weidenfeller","Lukasz Piszczek","Neven Subotic","Mats Hummels","Marcel Schmelzer","Sven Bender","Ilkay Gundogan","Jakub Blaszczykowski","Marco Reus","Mario Gotze","Robert Lewandowski"],
     "lineup_b_names":["Diego Lopez","Alvaro Arbeloa","Sergio Ramos","Raphael Varane","Fabio Coentrao","Xabi Alonso","Sami Khedira","Luka Modric","Mesut Ozil","Karim Benzema","Cristiano Ronaldo"]},
    {"match_id":"wc-group-2022-germany-japan","date":"2022-11-23","competition":"FIFA World Cup Group Stage","season":"2022",
     "opponent_a":"Germany","opponent_b":"Japan","score":"1-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Niklas Sule","Antonio Rudiger","Nico Schlotterbeck","David Raum","Joshua Kimmich","Ilkay Gundogan","Jamal Musiala","Serge Gnabry","Thomas Muller","Kai Havertz"],
     "lineup_b_names":["Shuichi Gonda","Hiroki Sakai","Maya Yoshida","Shogo Taniguchi","Yuto Nagatomo","Wataru Endo","Ao Tanaka","Junya Ito","Daichi Kamada","Takumi Minamino","Takefusa Kubo"]},
    {"match_id":"wc-group-2022-argentina-saudi","date":"2022-11-22","competition":"FIFA World Cup Group Stage","season":"2022",
     "opponent_a":"Argentina","opponent_b":"Saudi Arabia","score":"1-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Emiliano Martinez","Nahuel Molina","Cristian Romero","Nicolas Otamendi","Nicolas Tagliafico","Rodrigo De Paul","Leandro Paredes","Papu Gomez","Angel Di Maria","Lionel Messi","Lautaro Martinez"],
     "lineup_b_names":["Mohammed Al-Owais","Sultan Al-Ghannam","Abdulelah Al-Amri","Ali Al-Bulaihi","Yasser Al-Shahrani","Sami Al-Najei","Mohamed Kanno","Abdulellah Al-Malki","Feras Al-Brikan","Salem Al-Dawsari","Saleh Al-Shehri"]},
    {"match_id":"epl-manchester-derby-2022","date":"2022-10-02","competition":"Premier League","season":"2022-23",
     "opponent_a":"Manchester City","opponent_b":"Manchester United","score":"6-3",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Ederson","Kyle Walker","Manuel Akanji","Nathan Ake","Joao Cancelo","Kevin De Bruyne","Rodri","Bernardo Silva","Erling Haaland","Phil Foden","Jack Grealish"],
     "lineup_b_names":["David de Gea","Diogo Dalot","Raphael Varane","Lisandro Martinez","Tyrell Malacia","Casemiro","Christian Eriksen","Antony","Bruno Fernandes","Marcus Rashford","Jadon Sancho"]},
    {"match_id":"epl-north-london-derby-2023","date":"2023-10-01","competition":"Premier League","season":"2023-24",
     "opponent_a":"Arsenal","opponent_b":"Tottenham Hotspur","score":"2-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["David Raya","Ben White","William Saliba","Gabriel Magalhaes","Jurrien Timber","Declan Rice","Martin Odegaard","Bukayo Saka","Kai Havertz","Leandro Trossard","Gabriel Martinelli"],
     "lineup_b_names":["Guglielmo Vicario","Pedro Porro","Cristian Romero","Micky van de Ven","Destiny Udogie","Yves Bissouma","James Maddison","Dejan Kulusevski","Son Heung-min","Richarlison","Brennan Johnson"]},
    {"match_id":"ucl-sf-2022-city-real","date":"2022-05-04","competition":"UEFA Champions League Semi-Final","season":"2021-22",
     "opponent_a":"Real Madrid","opponent_b":"Manchester City","score":"3-1 (agg 6-5)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Thibaut Courtois","Dani Carvajal","Eder Militao","David Alaba","Ferland Mendy","Eduardo Camavinga","Luka Modric","Toni Kroos","Federico Valverde","Vinicius Junior","Karim Benzema"],
     "lineup_b_names":["Ederson","Kyle Walker","Ruben Dias","Aymeric Laporte","Joao Cancelo","Kevin De Bruyne","Rodri","Bernardo Silva","Riyad Mahrez","Phil Foden","Gabriel Jesus"]},
    {"match_id":"ucl-sf-2023-city-real","date":"2023-05-17","competition":"UEFA Champions League Semi-Final","season":"2022-23",
     "opponent_a":"Manchester City","opponent_b":"Real Madrid","score":"4-0 (agg 5-1)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Ederson","Kyle Walker","Ruben Dias","Manuel Akanji","Nathan Ake","Rodri","Kevin De Bruyne","Bernardo Silva","Jack Grealish","Erling Haaland","Phil Foden"],
     "lineup_b_names":["Thibaut Courtois","Dani Carvajal","Eder Militao","David Alaba","Ferland Mendy","Toni Kroos","Eduardo Camavinga","Luka Modric","Federico Valverde","Vinicius Junior","Karim Benzema"]},
    {"match_id":"serie-a-derby-2023","date":"2023-02-05","competition":"Serie A","season":"2022-23",
     "opponent_a":"Inter Milan","opponent_b":"AC Milan","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Andre Onana","Matteo Darmian","Stefan de Vrij","Alessandro Bastoni","Denzel Dumfries","Nicolo Barella","Hakan Calhanoglu","Henrikh Mkhitaryan","Federico Dimarco","Edin Dzeko","Lautaro Martinez"],
     "lineup_b_names":["Mike Maignan","Davide Calabria","Fikayo Tomori","Simon Kjaer","Theo Hernandez","Sandro Tonali","Ismael Bennacer","Brahim Diaz","Rafael Leao","Olivier Giroud","Ante Rebic"]},
    {"match_id":"ligue1-psg-marseille-2023","date":"2023-02-26","competition":"Ligue 1","season":"2022-23",
     "opponent_a":"Paris Saint-Germain","opponent_b":"Marseille","score":"3-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Gianluigi Donnarumma","Achraf Hakimi","Marquinhos","Presnel Kimpembe","Nuno Mendes","Vitinha","Marco Verratti","Fabian Ruiz","Kylian Mbappe","Neymar","Lionel Messi"],
     "lineup_b_names":["Pau Lopez","Jonathan Clauss","Samuel Gigot","Chancel Mbemba","Nuno Tavares","Jordan Veretout","Matteo Guendouzi","Amine Harit","Cengiz Under","Alexis Sanchez","Dimitri Payet"]},
    {"match_id":"bundesliga-bayern-dortmund-2023","date":"2023-04-01","competition":"Bundesliga","season":"2022-23",
     "opponent_a":"Bayern Munich","opponent_b":"Borussia Dortmund","score":"4-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Yann Sommer","Benjamin Pavard","Dayot Upamecano","Matthijs de Ligt","Alphonso Davies","Joshua Kimmich","Leon Goretzka","Jamal Musiala","Serge Gnabry","Leroy Sane","Eric Maxim Choupo-Moting"],
     "lineup_b_names":["Gregor Kobel","Thomas Meunier","Niklas Sule","Mats Hummels","Raphael Guerreiro","Jude Bellingham","Emre Can","Julian Brandt","Marco Reus","Donyell Malen","Sebastien Haller"]},
    {"match_id":"euro-final-2024","date":"2024-07-14","competition":"UEFA European Championship Final","season":"2024",
     "opponent_a":"Spain","opponent_b":"England","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Unai Simon","Dani Carvajal","Robin Le Normand","Aymeric Laporte","Marc Cucurella","Rodri","Fabian Ruiz","Dani Olmo","Lamine Yamal","Alvaro Morata","Nico Williams"],
     "lineup_b_names":["Jordan Pickford","Kyle Walker","John Stones","Marc Guehi","Luke Shaw","Declan Rice","Kobbie Mainoo","Bukayo Saka","Jude Bellingham","Phil Foden","Harry Kane"]},
    {"match_id":"euro-sf-2024-spain-france","date":"2024-07-09","competition":"UEFA European Championship Semi-Final","season":"2024",
     "opponent_a":"Spain","opponent_b":"France","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Unai Simon","Jesus Navas","Robin Le Normand","Aymeric Laporte","Marc Cucurella","Rodri","Fabian Ruiz","Dani Olmo","Lamine Yamal","Alvaro Morata","Nico Williams"],
     "lineup_b_names":["Mike Maignan","Jules Kounde","Dayot Upamecano","William Saliba","Theo Hernandez","Aurelien Tchouameni","N'Golo Kante","Ousmane Dembele","Antoine Griezmann","Kylian Mbappe","Randal Kolo Muani"]},
    {"match_id":"euro-sf-2024-england-netherlands","date":"2024-07-10","competition":"UEFA European Championship Semi-Final","season":"2024",
     "opponent_a":"England","opponent_b":"Netherlands","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Jordan Pickford","Kyle Walker","John Stones","Marc Guehi","Luke Shaw","Declan Rice","Kobbie Mainoo","Bukayo Saka","Jude Bellingham","Phil Foden","Harry Kane"],
     "lineup_b_names":["Bart Verbruggen","Denzel Dumfries","Stefan de Vrij","Virgil van Dijk","Nathan Ake","Jerdy Schouten","Xavi Simons","Tijjani Reijnders","Donyell Malen","Memphis Depay","Cody Gakpo"]},
    {"match_id":"epl-bayer-leverkusen-atalanta-2024","date":"2024-05-22","competition":"UEFA Europa League Final","season":"2023-24",
     "opponent_a":"Bayer Leverkusen","opponent_b":"Atalanta","score":"0-3",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Lukas Hradecky","Odilon Kossounou","Jonathan Tah","Edmond Tapsoba","Alejandro Grimaldo","Robert Andrich","Granit Xhaka","Florian Wirtz","Jeremie Frimpong","Victor Boniface","Amine Adli"],
     "lineup_b_names":["Juan Musso","Berat Djimsiti","Isak Hien","Sead Kolasinac","Davide Zappacosta","Ederson","Marten de Roon","Teun Koopmeiners","Mario Pasalic","Ademola Lookman","Gianluca Scamacca"]},
    {"match_id":"ucl-sf-2019-ajax-spurs","date":"2019-05-08","competition":"UEFA Champions League Semi-Final","season":"2018-19",
     "opponent_a":"Ajax","opponent_b":"Tottenham Hotspur","score":"2-3 (agg 3-3, away goals)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Andre Onana","Joel Veltman","Matthijs de Ligt","Daley Blind","Nicolas Tagliafico","Lasse Schone","Frenkie de Jong","Donny van de Beek","Hakim Ziyech","Dusan Tadic","David Neres"],
     "lineup_b_names":["Hugo Lloris","Kieran Trippier","Toby Alderweireld","Jan Vertonghen","Danny Rose","Moussa Sissoko","Victor Wanyama","Dele Alli","Christian Eriksen","Son Heung-min","Lucas Moura"]},
    {"match_id":"la-liga-clasico-2023","date":"2023-10-28","competition":"La Liga","season":"2023-24",
     "opponent_a":"Barcelona","opponent_b":"Real Madrid","score":"1-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Marc-Andre ter Stegen","Jules Kounde","Ronald Araujo","Andreas Christensen","Alejandro Balde","Gavi","Pedri","Frenkie de Jong","Lamine Yamal","Robert Lewandowski","Joao Felix"],
     "lineup_b_names":["Andriy Lunin","Dani Carvajal","Antonio Rudiger","David Alaba","Ferland Mendy","Federico Valverde","Toni Kroos","Jude Bellingham","Rodrygo","Vinicius Junior","Joselu"]},
    {"match_id":"epl-man-city-arsenal-2024","date":"2024-03-31","competition":"Premier League","season":"2023-24",
     "opponent_a":"Arsenal","opponent_b":"Manchester City","score":"0-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["David Raya","Ben White","William Saliba","Gabriel Magalhaes","Oleksandr Zinchenko","Declan Rice","Jorginho","Martin Odegaard","Bukayo Saka","Kai Havertz","Leandro Trossard"],
     "lineup_b_names":["Ederson","Kyle Walker","Ruben Dias","Nathan Ake","Josko Gvardiol","Rodri","Bernardo Silva","Kevin De Bruyne","Phil Foden","Erling Haaland","Jeremy Doku"]},
    {"match_id":"wc-group-2014-spain-netherlands","date":"2014-06-13","competition":"FIFA World Cup Group Stage","season":"2014",
     "opponent_a":"Spain","opponent_b":"Netherlands","score":"1-5",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Iker Casillas","Juanfran","Sergio Ramos","Gerard Pique","Jordi Alba","Xabi Alonso","Sergio Busquets","Xavi","David Silva","Diego Costa","Pedro Rodriguez"],
     "lineup_b_names":["Jasper Cillessen","Daryl Janmaat","Ron Vlaar","Stefan de Vrij","Daley Blind","Georginio Wijnaldum","Nigel de Jong","Jonathan de Guzman","Wesley Sneijder","Arjen Robben","Robin van Persie"]},
    {"match_id":"wc-group-2018-germany-mexico","date":"2018-06-17","competition":"FIFA World Cup Group Stage","season":"2018",
     "opponent_a":"Germany","opponent_b":"Mexico","score":"0-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Joshua Kimmich","Jerome Boateng","Mats Hummels","Jonas Hector","Sami Khedira","Toni Kroos","Mesut Ozil","Thomas Muller","Timo Werner","Julian Draxler"],
     "lineup_b_names":["Guillermo Ochoa","Jesus Gallardo","Hugo Ayala","Hector Moreno","Carlos Salcedo","Andres Guardado","Hector Herrera","Miguel Layun","Hirving Lozano","Javier Hernandez","Carlos Vela"]},
    {"match_id":"wc-group-2014-germany-portugal","date":"2014-06-16","competition":"FIFA World Cup Group Stage","season":"2014",
     "opponent_a":"Germany","opponent_b":"Portugal","score":"4-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Philipp Lahm","Mats Hummels","Jerome Boateng","Benedikt Howedes","Sami Khedira","Bastian Schweinsteiger","Toni Kroos","Mesut Ozil","Thomas Muller","Mario Gotze"],
     "lineup_b_names":["Rui Patricio","Joao Pereira","Pepe","Bruno Alves","Fabio Coentrao","Miguel Veloso","William Carvalho","Joao Moutinho","Nani","Hugo Almeida","Cristiano Ronaldo"]},
    {"match_id":"wc-sf-2010-germany-spain","date":"2010-07-07","competition":"FIFA World Cup Semi-Final","season":"2010",
     "opponent_a":"Germany","opponent_b":"Spain","score":"0-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Philipp Lahm","Arne Friedrich","Per Mertesacker","Jerome Boateng","Bastian Schweinsteiger","Sami Khedira","Mesut Ozil","Thomas Muller","Miroslav Klose","Lukas Podolski"],
     "lineup_b_names":["Iker Casillas","Sergio Ramos","Carles Puyol","Gerard Pique","Joan Capdevila","Xabi Alonso","Sergio Busquets","Xavi","Andres Iniesta","David Villa","Pedro Rodriguez"]},
    {"match_id":"wc-sf-2018-france-belgium","date":"2018-07-10","competition":"FIFA World Cup Semi-Final","season":"2018",
     "opponent_a":"France","opponent_b":"Belgium","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Hugo Lloris","Benjamin Pavard","Raphael Varane","Samuel Umtiti","Lucas Hernandez","N'Golo Kante","Paul Pogba","Blaise Matuidi","Kylian Mbappe","Antoine Griezmann","Olivier Giroud"],
     "lineup_b_names":["Thibaut Courtois","Thomas Meunier","Toby Alderweireld","Vincent Kompany","Jan Vertonghen","Axel Witsel","Marouane Fellaini","Kevin De Bruyne","Nacer Chadli","Eden Hazard","Romelu Lukaku"]},
    {"match_id":"epl-leicester-5000-1","date":"2016-05-07","competition":"Premier League","season":"2015-16",
     "opponent_a":"Leicester City","opponent_b":"Everton","score":"3-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Kasper Schmeichel","Danny Simpson","Wes Morgan","Robert Huth","Christian Fuchs","Riyad Mahrez","N'Golo Kante","Danny Drinkwater","Marc Albrighton","Jamie Vardy","Andy King"],
     "lineup_b_names":["Joel Robles","Seamus Coleman","John Stones","Phil Jagielka","Leighton Baines","James McCarthy","Gareth Barry","Ross Barkley","Kevin Mirallas","Romelu Lukaku","Aaron Lennon"]},
    {"match_id":"ucl-sf-2012-chelsea-barca","date":"2012-04-24","competition":"UEFA Champions League Semi-Final","season":"2011-12",
     "opponent_a":"Barcelona","opponent_b":"Chelsea","score":"2-2 (agg 2-3)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Victor Valdes","Dani Alves","Gerard Pique","Javier Mascherano","Adriano","Sergio Busquets","Xavi","Andres Iniesta","Cesc Fabregas","Lionel Messi","Alexis Sanchez"],
     "lineup_b_names":["Petr Cech","Jose Bosingwa","Gary Cahill","John Terry","Ashley Cole","Ramires","Jon Obi Mikel","Salomon Kalou","Frank Lampard","Juan Mata","Didier Drogba"]},
    {"match_id":"ucl-sf-2014-real-bayern","date":"2014-04-29","competition":"UEFA Champions League Semi-Final","season":"2013-14",
     "opponent_a":"Bayern Munich","opponent_b":"Real Madrid","score":"0-4 (agg 0-5)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Philipp Lahm","Jerome Boateng","Dante","David Alaba","Bastian Schweinsteiger","Toni Kroos","Arjen Robben","Thomas Muller","Franck Ribery","Mario Mandzukic"],
     "lineup_b_names":["Iker Casillas","Dani Carvajal","Sergio Ramos","Pepe","Fabio Coentrao","Angel Di Maria","Xabi Alonso","Luka Modric","Gareth Bale","Karim Benzema","Cristiano Ronaldo"]},
    {"match_id":"ucl-sf-2009-chelsea-barca","date":"2009-05-06","competition":"UEFA Champions League Semi-Final","season":"2008-09",
     "opponent_a":"Chelsea","opponent_b":"Barcelona","score":"1-1 (agg 1-1, away goals)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Petr Cech","Jose Bosingwa","Alex","John Terry","Ashley Cole","Michael Essien","Michael Ballack","Frank Lampard","Florent Malouda","Nicolas Anelka","Didier Drogba"],
     "lineup_b_names":["Victor Valdes","Dani Alves","Gerard Pique","Carles Puyol","Eric Abidal","Xavi","Sergio Busquets","Yaya Toure","Andres Iniesta","Lionel Messi","Samuel Eto'o"]},
    {"match_id":"ucl-sf-2018-roma-liverpool","date":"2018-05-02","competition":"UEFA Champions League Semi-Final","season":"2017-18",
     "opponent_a":"Roma","opponent_b":"Liverpool","score":"4-2 (agg 6-7)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Alisson","Alessandro Florenzi","Federico Fazio","Juan Jesus","Aleksandar Kolarov","Daniele De Rossi","Lorenzo Pellegrini","Nainggolan","Cengiz Under","Edin Dzeko","Stephan El Shaarawy"],
     "lineup_b_names":["Loris Karius","Trent Alexander-Arnold","Dejan Lovren","Virgil van Dijk","Andrew Robertson","Jordan Henderson","James Milner","Georginio Wijnaldum","Mohamed Salah","Roberto Firmino","Sadio Mane"]},
    {"match_id":"ucl-sf-2020-lyon-bayern","date":"2020-08-19","competition":"UEFA Champions League Semi-Final","season":"2019-20",
     "opponent_a":"Lyon","opponent_b":"Bayern Munich","score":"0-3",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Anthony Lopes","Leo Dubois","Jason Denayer","Marcelo","Maxwel Cornet","Bruno Guimaraes","Houssem Aouar","Maxence Caqueret","Karl Toko Ekambi","Memphis Depay","Moussa Dembele"],
     "lineup_b_names":["Manuel Neuer","Joshua Kimmich","Jerome Boateng","David Alaba","Alphonso Davies","Leon Goretzka","Thiago Alcantara","Serge Gnabry","Thomas Muller","Ivan Perisic","Robert Lewandowski"]},
    {"match_id":"wc-qf-2022-netherlands-argentina","date":"2022-12-09","competition":"FIFA World Cup Quarter-Final","season":"2022",
     "opponent_a":"Netherlands","opponent_b":"Argentina","score":"2-2 (3-4 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Andries Noppert","Jurrien Timber","Virgil van Dijk","Nathan Ake","Denzel Dumfries","Steven Berghuis","Frenkie de Jong","Marten de Roon","Davy Klaassen","Memphis Depay","Cody Gakpo"],
     "lineup_b_names":["Emiliano Martinez","Nahuel Molina","Cristian Romero","Nicolas Otamendi","Nicolas Tagliafico","Rodrigo De Paul","Enzo Fernandez","Alexis Mac Allister","Angel Di Maria","Lionel Messi","Julian Alvarez"]},
    {"match_id":"wc-r16-2022-japan-croatia","date":"2022-12-05","competition":"FIFA World Cup Round of 16","season":"2022",
     "opponent_a":"Japan","opponent_b":"Croatia","score":"1-1 (1-3 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Shuichi Gonda","Hiroki Sakai","Maya Yoshida","Shogo Taniguchi","Yuto Nagatomo","Wataru Endo","Ao Tanaka","Junya Ito","Daichi Kamada","Ritsu Doan","Daizen Maeda"],
     "lineup_b_names":["Dominik Livakovic","Josip Juranovic","Dejan Lovren","Josko Gvardiol","Borna Sosa","Luka Modric","Marcelo Brozovic","Mateo Kovacic","Ivan Perisic","Andrej Kramaric","Bruno Petkovic"]},
]

print(f"Total matches: {len(matches)}")

with open("/Users/jasur/workspace/football/data/matches_db.json", "w") as f:
    json.dump(matches, f, indent=2, ensure_ascii=False)
print("matches_db.json written successfully!")
