#!/usr/bin/env python3
"""Add more matches to reach 200+."""
import json

existing = json.load(open("/Users/jasur/workspace/football/data/matches_db.json"))
existing_ids = {m["match_id"] for m in existing}
z = [0]*11

more = [
    # More Premier League classics
    {"match_id":"epl-arsenal-invincibles-2004","date":"2004-05-15","competition":"Premier League","season":"2003-04",
     "opponent_a":"Arsenal","opponent_b":"Leicester City","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Jens Lehmann","Lauren","Kolo Toure","Sol Campbell","Ashley Cole","Patrick Vieira","Gilberto Silva","Robert Pires","Freddie Ljungberg","Thierry Henry","Dennis Bergkamp"],
     "lineup_b_names":["Ian Walker","Riccardo Scimeca","Nikos Dabizas","Matt Elliott","Jordan Stewart","Ben Thatcher","Muzzy Izzet","Lilian Nalis","Paul Dickov","Les Ferdinand","Marcus Bent"]},
    {"match_id":"epl-manu-city-1999-fa-cup","date":"1999-04-14","competition":"FA Cup Semi-Final","season":"1998-99",
     "opponent_a":"Manchester United","opponent_b":"Arsenal","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Peter Schmeichel","Gary Neville","Denis Irwin","Jaap Stam","Phil Neville","David Beckham","Roy Keane","Paul Scholes","Ryan Giggs","Andy Cole","Dwight Yorke"],
     "lineup_b_names":["David Seaman","Lee Dixon","Tony Adams","Martin Keown","Nigel Winterburn","Patrick Vieira","Emmanuel Petit","Ray Parlour","Marc Overmars","Dennis Bergkamp","Nicolas Anelka"]},
    {"match_id":"epl-liverpool-ac-milan-2005-group","date":"2004-12-08","competition":"UEFA Champions League Group Stage","season":"2004-05",
     "opponent_a":"Liverpool","opponent_b":"Olympiacos","score":"3-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Chris Kirkland","Steve Finnan","Jamie Carragher","Sami Hyypia","Djimi Traore","Steven Gerrard","Xabi Alonso","Dietmar Hamann","Harry Kewell","Milan Baros","Florent Sinama-Pongolle"],
     "lineup_b_names":["Antonios Nikopolidis","Stylianos Venetidis","Gabriel","Fragiskos Gerolemou","Giorgos Anatolakis","Predrag Djordjevic","Anastasios Pantos","Stelios Giannakopoulos","Ieroklis Stoltidis","Giovanni","Rivaldo"]},
    {"match_id":"epl-chelsea-arsenal-2-0-2004","date":"2004-10-24","competition":"Premier League","season":"2004-05",
     "opponent_a":"Manchester United","opponent_b":"Arsenal","score":"2-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Roy Carroll","Gary Neville","Rio Ferdinand","Mikael Silvestre","Gabriel Heinze","Cristiano Ronaldo","Paul Scholes","Roy Keane","Ryan Giggs","Wayne Rooney","Ruud van Nistelrooy"],
     "lineup_b_names":["Jens Lehmann","Lauren","Kolo Toure","Sol Campbell","Ashley Cole","Patrick Vieira","Gilberto Silva","Robert Pires","Freddie Ljungberg","Thierry Henry","Jose Antonio Reyes"]},
    # More La Liga/El Clasico
    {"match_id":"clasico-2005-11-19","date":"2005-11-19","competition":"La Liga","season":"2005-06",
     "opponent_a":"Barcelona","opponent_b":"Real Madrid","score":"3-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Victor Valdes","Oleguer","Carles Puyol","Rafael Marquez","Giovanni van Bronckhorst","Deco","Edmilson","Xavi","Ludovic Giuly","Ronaldinho","Samuel Eto'o"],
     "lineup_b_names":["Iker Casillas","Michel Salgado","Sergio Ramos","Ivan Helguera","Roberto Carlos","Beckham","Guti","Zidane","Raul","Robinho","Ronaldo"]},
    {"match_id":"clasico-2010-11-29","date":"2010-11-29","competition":"La Liga","season":"2010-11",
     "opponent_a":"Barcelona","opponent_b":"Real Madrid","score":"5-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Victor Valdes","Dani Alves","Gerard Pique","Carles Puyol","Eric Abidal","Xavi","Sergio Busquets","Andres Iniesta","Lionel Messi","David Villa","Pedro Rodriguez"],
     "lineup_b_names":["Iker Casillas","Sergio Ramos","Pepe","Ricardo Carvalho","Marcelo","Xabi Alonso","Sami Khedira","Angel Di Maria","Mesut Ozil","Cristiano Ronaldo","Karim Benzema"]},
    {"match_id":"clasico-2011-supercopa","date":"2011-08-17","competition":"Supercopa de Espana","season":"2011-12",
     "opponent_a":"Barcelona","opponent_b":"Real Madrid","score":"3-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Victor Valdes","Dani Alves","Gerard Pique","Javier Mascherano","Adriano","Xavi","Sergio Busquets","Andres Iniesta","Cesc Fabregas","Lionel Messi","David Villa"],
     "lineup_b_names":["Iker Casillas","Sergio Ramos","Pepe","Fabio Coentrao","Marcelo","Xabi Alonso","Sami Khedira","Angel Di Maria","Mesut Ozil","Cristiano Ronaldo","Karim Benzema"]},
    {"match_id":"clasico-2014-03-23","date":"2014-03-23","competition":"La Liga","season":"2013-14",
     "opponent_a":"Real Madrid","opponent_b":"Barcelona","score":"3-4",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Iker Casillas","Dani Carvajal","Sergio Ramos","Pepe","Marcelo","Angel Di Maria","Xabi Alonso","Luka Modric","Gareth Bale","Karim Benzema","Cristiano Ronaldo"],
     "lineup_b_names":["Victor Valdes","Dani Alves","Gerard Pique","Javier Mascherano","Jordi Alba","Sergio Busquets","Xavi","Andres Iniesta","Cesc Fabregas","Lionel Messi","Neymar"]},
    # More Serie A derbies
    {"match_id":"serie-a-milan-derby-2003","date":"2003-05-07","competition":"UEFA Champions League Semi-Final","season":"2002-03",
     "opponent_a":"AC Milan","opponent_b":"Inter Milan","score":"1-1 (agg 1-1, away goals)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Dida","Cafu","Paolo Maldini","Alessandro Nesta","Alessandro Costacurta","Gennaro Gattuso","Andrea Pirlo","Clarence Seedorf","Rui Costa","Rivaldo","Andriy Shevchenko"],
     "lineup_b_names":["Francesco Toldo","Javier Zanetti","Fabio Cannavaro","Ivan Cordoba","Giovanni Pasquale","Cristiano Zanetti","Emre Belozoglu","Sergio Conceicao","Kily Gonzalez","Christian Vieri","Hernan Crespo"]},
    {"match_id":"serie-a-juve-inter-2018","date":"2018-04-28","competition":"Serie A","season":"2017-18",
     "opponent_a":"Juventus","opponent_b":"Inter Milan","score":"0-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Gianluigi Buffon","Stephan Lichtsteiner","Giorgio Chiellini","Andrea Barzagli","Alex Sandro","Miralem Pjanic","Blaise Matuidi","Sami Khedira","Douglas Costa","Gonzalo Higuain","Mario Mandzukic"],
     "lineup_b_names":["Samir Handanovic","Danilo D'Ambrosio","Milan Skriniar","Miranda","Stefan de Vrij","Marcelo Brozovic","Borja Valero","Ivan Perisic","Joao Mario","Mauro Icardi","Antonio Candreva"]},
    # More Bundesliga
    {"match_id":"bundesliga-klassiker-2020","date":"2020-11-07","competition":"Bundesliga","season":"2020-21",
     "opponent_a":"Borussia Dortmund","opponent_b":"Bayern Munich","score":"2-3",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Roman Burki","Thomas Meunier","Mats Hummels","Manuel Akanji","Raphael Guerreiro","Axel Witsel","Thomas Delaney","Giovanni Reyna","Marco Reus","Jadon Sancho","Erling Haaland"],
     "lineup_b_names":["Manuel Neuer","Benjamin Pavard","Jerome Boateng","David Alaba","Alphonso Davies","Joshua Kimmich","Leon Goretzka","Serge Gnabry","Thomas Muller","Kingsley Coman","Robert Lewandowski"]},
    {"match_id":"bundesliga-leverkusen-invincible-2024","date":"2024-04-14","competition":"Bundesliga","season":"2023-24",
     "opponent_a":"Bayer Leverkusen","opponent_b":"Werder Bremen","score":"5-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Lukas Hradecky","Odilon Kossounou","Jonathan Tah","Edmond Tapsoba","Alejandro Grimaldo","Robert Andrich","Granit Xhaka","Florian Wirtz","Jeremie Frimpong","Victor Boniface","Nathan Tella"],
     "lineup_b_names":["Michael Zetterer","Amos Pieper","Milos Veljkovic","Marco Friedl","Felix Agu","Mitchell Weiser","Senne Lynen","Romano Schmid","Leonardo Bittencourt","Niclas Fullkrug","Marvin Ducksch"]},
    # More World Cup matches from different eras
    {"match_id":"wc-final-1986","date":"1986-06-29","competition":"FIFA World Cup Final","season":"1986",
     "opponent_a":"Argentina","opponent_b":"West Germany","score":"3-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Nery Pumpido","Jose Luis Cuciuffo","Oscar Ruggeri","Jose Luis Brown","Julio Olarticoechea","Sergio Batista","Hector Enrique","Jorge Burruchaga","Jorge Valdano","Diego Maradona","Jorge Burrachaga"],
     "lineup_b_names":["Harald Schumacher","Thomas Berthold","Karl-Heinz Forster","Hans-Peter Briegel","Andreas Brehme","Norbert Eder","Felix Magath","Lothar Matthaus","Karl-Heinz Rummenigge","Rudi Voller","Ditmar Jakobs"]},
    {"match_id":"wc-qf-1986-argentina-england","date":"1986-06-22","competition":"FIFA World Cup Quarter-Final","season":"1986",
     "opponent_a":"Argentina","opponent_b":"England","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Nery Pumpido","Jose Luis Cuciuffo","Oscar Ruggeri","Jose Luis Brown","Julio Olarticoechea","Sergio Batista","Hector Enrique","Jorge Burruchaga","Jorge Valdano","Diego Maradona","Carlos Tapia"],
     "lineup_b_names":["Peter Shilton","Gary Stevens","Terry Fenwick","Terry Butcher","Kenny Sansom","Steve Hodge","Glenn Hoddle","Peter Reid","Peter Beardsley","Gary Lineker","Trevor Steven"]},
    {"match_id":"wc-final-1970","date":"1970-06-21","competition":"FIFA World Cup Final","season":"1970",
     "opponent_a":"Brazil","opponent_b":"Italy","score":"4-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Felix","Carlos Alberto","Brito","Piazza","Everaldo","Clodoaldo","Gerson","Jairzinho","Tostao","Pele","Rivelino"],
     "lineup_b_names":["Enrico Albertosi","Tarcisio Burgnich","Giacinto Facchetti","Roberto Rosato","Pierluigi Cera","Gianni Rivera","Sandro Mazzola","Angelo Domenghini","Roberto Boninsegna","Gigi Riva","Mario Bertini"]},
    {"match_id":"wc-final-1966","date":"1966-07-30","competition":"FIFA World Cup Final","season":"1966",
     "opponent_a":"England","opponent_b":"West Germany","score":"4-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Gordon Banks","George Cohen","Jack Charlton","Bobby Moore","Ray Wilson","Nobby Stiles","Bobby Charlton","Martin Peters","Alan Ball","Geoff Hurst","Roger Hunt"],
     "lineup_b_names":["Hans Tilkowski","Horst-Dieter Hottges","Willi Schulz","Wolfgang Weber","Karl-Heinz Schnellinger","Franz Beckenbauer","Wolfgang Overath","Helmut Haller","Uwe Seeler","Sigfried Held","Lothar Emmerich"]},
    {"match_id":"wc-sf-2010-spain-germany","date":"2010-07-07","competition":"FIFA World Cup Semi-Final","season":"2010",
     "opponent_a":"Spain","opponent_b":"Germany","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Iker Casillas","Sergio Ramos","Gerard Pique","Carles Puyol","Joan Capdevila","Xavi","Sergio Busquets","Xabi Alonso","Andres Iniesta","Pedro Rodriguez","David Villa"],
     "lineup_b_names":["Manuel Neuer","Philipp Lahm","Per Mertesacker","Arne Friedrich","Jerome Boateng","Bastian Schweinsteiger","Sami Khedira","Mesut Ozil","Thomas Muller","Miroslav Klose","Lukas Podolski"]},
    # More Champions League knockouts
    {"match_id":"ucl-qf-2019-mancity-spurs","date":"2019-04-17","competition":"UEFA Champions League Quarter-Final","season":"2018-19",
     "opponent_a":"Manchester City","opponent_b":"Tottenham Hotspur","score":"4-3 (agg 4-4, away goals)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Ederson","Kyle Walker","Nicolas Otamendi","Aymeric Laporte","Benjamin Mendy","Kevin De Bruyne","Ilkay Gundogan","Bernardo Silva","Raheem Sterling","Sergio Aguero","Leroy Sane"],
     "lineup_b_names":["Hugo Lloris","Kieran Trippier","Toby Alderweireld","Jan Vertonghen","Danny Rose","Moussa Sissoko","Eric Dier","Dele Alli","Christian Eriksen","Son Heung-min","Fernando Llorente"]},
    {"match_id":"ucl-qf-2018-roma-barca","date":"2018-04-10","competition":"UEFA Champions League Quarter-Final","season":"2017-18",
     "opponent_a":"Roma","opponent_b":"Barcelona","score":"3-0 (agg 4-4, away goals)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Alisson","Alessandro Florenzi","Federico Fazio","Kostas Manolas","Aleksandar Kolarov","Daniele De Rossi","Nainggolan","Kevin Strootman","Cengiz Under","Edin Dzeko","Stephan El Shaarawy"],
     "lineup_b_names":["Marc-Andre ter Stegen","Nelson Semedo","Gerard Pique","Samuel Umtiti","Jordi Alba","Sergio Busquets","Ivan Rakitic","Andres Iniesta","Ousmane Dembele","Lionel Messi","Luis Suarez"]},
    {"match_id":"ucl-r16-2017-barca-psg","date":"2017-03-08","competition":"UEFA Champions League Round of 16","season":"2016-17",
     "opponent_a":"Barcelona","opponent_b":"Paris Saint-Germain","score":"6-1 (agg 6-5)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Marc-Andre ter Stegen","Sergi Roberto","Gerard Pique","Samuel Umtiti","Jordi Alba","Sergio Busquets","Ivan Rakitic","Andres Iniesta","Rafinha","Lionel Messi","Neymar"],
     "lineup_b_names":["Kevin Trapp","Thomas Meunier","Marquinhos","Presnel Kimpembe","Layvin Kurzawa","Marco Verratti","Adrien Rabiot","Blaise Matuidi","Julian Draxler","Edinson Cavani","Angel Di Maria"]},
    {"match_id":"ucl-r16-2019-manu-psg","date":"2019-03-06","competition":"UEFA Champions League Round of 16","season":"2018-19",
     "opponent_a":"Paris Saint-Germain","opponent_b":"Manchester United","score":"1-3 (agg 3-3, away goals)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Gianluigi Buffon","Thilo Kehrer","Presnel Kimpembe","Marquinhos","Juan Bernat","Dani Alves","Marco Verratti","Julian Draxler","Angel Di Maria","Kylian Mbappe","Eric Choupo-Moting"],
     "lineup_b_names":["David de Gea","Ashley Young","Eric Bailly","Chris Smalling","Luke Shaw","Scott McTominay","Fred","Andreas Pereira","Mason Greenwood","Marcus Rashford","Romelu Lukaku"]},
    {"match_id":"ucl-sf-2023-inter-city","date":"2023-05-16","competition":"UEFA Champions League Semi-Final","season":"2022-23",
     "opponent_a":"Inter Milan","opponent_b":"AC Milan","score":"1-0 (agg 3-0)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Andre Onana","Matteo Darmian","Francesco Acerbi","Alessandro Bastoni","Denzel Dumfries","Nicolo Barella","Hakan Calhanoglu","Henrikh Mkhitaryan","Federico Dimarco","Lautaro Martinez","Romelu Lukaku"],
     "lineup_b_names":["Mike Maignan","Davide Calabria","Fikayo Tomori","Malick Thiaw","Theo Hernandez","Sandro Tonali","Ismael Bennacer","Brahim Diaz","Junior Messias","Rafael Leao","Olivier Giroud"]},
    # More internationals
    {"match_id":"euro-sf-2016-germany-france","date":"2016-07-07","competition":"UEFA European Championship Semi-Final","season":"2016",
     "opponent_a":"Germany","opponent_b":"France","score":"0-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Manuel Neuer","Joshua Kimmich","Jerome Boateng","Mats Hummels","Jonas Hector","Bastian Schweinsteiger","Toni Kroos","Mesut Ozil","Thomas Muller","Julian Draxler","Mario Gomez"],
     "lineup_b_names":["Hugo Lloris","Bacary Sagna","Samuel Umtiti","Laurent Koscielny","Patrice Evra","Blaise Matuidi","N'Golo Kante","Paul Pogba","Moussa Sissoko","Antoine Griezmann","Olivier Giroud"]},
    {"match_id":"nations-league-2021-spain-france","date":"2021-10-10","competition":"UEFA Nations League Final","season":"2020-21",
     "opponent_a":"Spain","opponent_b":"France","score":"1-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Unai Simon","Cesar Azpilicueta","Eric Garcia","Aymeric Laporte","Marcos Alonso","Gavi","Sergio Busquets","Rodri","Yeremi Pino","Mikel Oyarzabal","Pablo Sarabia"],
     "lineup_b_names":["Hugo Lloris","Jules Kounde","Raphael Varane","Dayot Upamecano","Theo Hernandez","Aurelien Tchouameni","Paul Pogba","Antoine Griezmann","Ousmane Dembele","Kylian Mbappe","Karim Benzema"]},
    {"match_id":"copa-america-sf-2019-brazil-argentina","date":"2019-07-02","competition":"Copa America Semi-Final","season":"2019",
     "opponent_a":"Brazil","opponent_b":"Argentina","score":"2-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Alisson","Dani Alves","Marquinhos","Thiago Silva","Alex Sandro","Arthur","Casemiro","Philippe Coutinho","Gabriel Jesus","Roberto Firmino","Richarlison"],
     "lineup_b_names":["Franco Armani","Renzo Saravia","German Pezzella","Nicolas Otamendi","Nicolas Tagliafico","Rodrigo De Paul","Leandro Paredes","Giovani Lo Celso","Angel Di Maria","Lionel Messi","Sergio Aguero"]},
    # Additional EPL derby matches
    {"match_id":"epl-liverpool-mancity-2019","date":"2019-11-10","competition":"Premier League","season":"2019-20",
     "opponent_a":"Liverpool","opponent_b":"Manchester City","score":"3-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Alisson","Trent Alexander-Arnold","Dejan Lovren","Virgil van Dijk","Andrew Robertson","Fabinho","Jordan Henderson","Georginio Wijnaldum","Mohamed Salah","Roberto Firmino","Sadio Mane"],
     "lineup_b_names":["Claudio Bravo","Kyle Walker","John Stones","Fernandinho","Angelino","Ilkay Gundogan","Rodri","Kevin De Bruyne","Bernardo Silva","Sergio Aguero","Raheem Sterling"]},
    {"match_id":"epl-mancity-liverpool-2022","date":"2022-04-10","competition":"Premier League","season":"2021-22",
     "opponent_a":"Manchester City","opponent_b":"Liverpool","score":"2-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Ederson","Joao Cancelo","Aymeric Laporte","John Stones","Kyle Walker","Rodri","Kevin De Bruyne","Bernardo Silva","Raheem Sterling","Gabriel Jesus","Phil Foden"],
     "lineup_b_names":["Alisson","Trent Alexander-Arnold","Ibrahima Konate","Virgil van Dijk","Andrew Robertson","Fabinho","Thiago Alcantara","Jordan Henderson","Mohamed Salah","Sadio Mane","Luis Diaz"]},
    {"match_id":"epl-chelsea-tottenham-2016","date":"2016-05-02","competition":"Premier League","season":"2015-16",
     "opponent_a":"Chelsea","opponent_b":"Tottenham Hotspur","score":"2-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Asmir Begovic","Branislav Ivanovic","Gary Cahill","John Terry","Cesar Azpilicueta","Cesc Fabregas","John Obi Mikel","Willian","Eden Hazard","Pedro","Diego Costa"],
     "lineup_b_names":["Hugo Lloris","Kyle Walker","Toby Alderweireld","Jan Vertonghen","Danny Rose","Mousa Dembele","Eric Dier","Dele Alli","Christian Eriksen","Son Heung-min","Harry Kane"]},
    {"match_id":"epl-arsenal-leicester-2016","date":"2016-02-14","competition":"Premier League","season":"2015-16",
     "opponent_a":"Arsenal","opponent_b":"Leicester City","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Petr Cech","Hector Bellerin","Per Mertesacker","Laurent Koscielny","Nacho Monreal","Francis Coquelin","Aaron Ramsey","Mesut Ozil","Alexis Sanchez","Theo Walcott","Olivier Giroud"],
     "lineup_b_names":["Kasper Schmeichel","Danny Simpson","Wes Morgan","Robert Huth","Christian Fuchs","Riyad Mahrez","N'Golo Kante","Danny Drinkwater","Marc Albrighton","Jamie Vardy","Shinji Okazaki"]},
    # More World Cup classics
    {"match_id":"wc-group-2022-spain-japan","date":"2022-12-01","competition":"FIFA World Cup Group Stage","season":"2022",
     "opponent_a":"Japan","opponent_b":"Spain","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Shuichi Gonda","Hiroki Sakai","Takehiro Tomiyasu","Shogo Taniguchi","Yuto Nagatomo","Wataru Endo","Ao Tanaka","Junya Ito","Ritsu Doan","Daizen Maeda","Kaoru Mitoma"],
     "lineup_b_names":["Unai Simon","Cesar Azpilicueta","Rodri","Pau Torres","Jordi Alba","Gavi","Sergio Busquets","Pedri","Dani Olmo","Ferran Torres","Alvaro Morata"]},
    {"match_id":"wc-r16-2022-morocco-spain","date":"2022-12-06","competition":"FIFA World Cup Round of 16","season":"2022",
     "opponent_a":"Morocco","opponent_b":"Spain","score":"0-0 (3-0 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Yassine Bounou","Achraf Hakimi","Nayef Aguerd","Romain Saiss","Noussair Mazraoui","Azzedine Ounahi","Sofyan Amrabat","Selim Amallah","Hakim Ziyech","Youssef En-Nesyri","Sofiane Boufal"],
     "lineup_b_names":["Unai Simon","Marcos Llorente","Rodri","Aymeric Laporte","Jordi Alba","Gavi","Sergio Busquets","Pedri","Dani Olmo","Alvaro Morata","Ferran Torres"]},
    {"match_id":"wc-qf-2022-morocco-portugal","date":"2022-12-10","competition":"FIFA World Cup Quarter-Final","season":"2022",
     "opponent_a":"Morocco","opponent_b":"Portugal","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Yassine Bounou","Achraf Hakimi","Romain Saiss","Nayef Aguerd","Jawad El Yamiq","Azzedine Ounahi","Sofyan Amrabat","Selim Amallah","Hakim Ziyech","Youssef En-Nesyri","Sofiane Boufal"],
     "lineup_b_names":["Diogo Costa","Diogo Dalot","Pepe","Ruben Dias","Raphael Guerreiro","Ruben Neves","Bernardo Silva","Bruno Fernandes","Joao Felix","Cristiano Ronaldo","Goncalo Ramos"]},
    {"match_id":"wc-qf-2022-england-france","date":"2022-12-10","competition":"FIFA World Cup Quarter-Final","season":"2022",
     "opponent_a":"England","opponent_b":"France","score":"1-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Jordan Pickford","Kyle Walker","John Stones","Harry Maguire","Luke Shaw","Declan Rice","Jude Bellingham","Mason Mount","Bukayo Saka","Harry Kane","Phil Foden"],
     "lineup_b_names":["Hugo Lloris","Jules Kounde","Raphael Varane","Dayot Upamecano","Theo Hernandez","Aurelien Tchouameni","Adrien Rabiot","Ousmane Dembele","Antoine Griezmann","Kylian Mbappe","Olivier Giroud"]},
    # Serie A classics
    {"match_id":"serie-a-napoli-juve-2023-scudetto","date":"2023-04-30","competition":"Serie A","season":"2022-23",
     "opponent_a":"Napoli","opponent_b":"Juventus","score":"0-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Alex Meret","Giovanni Di Lorenzo","Min-jae Kim","Amir Rrahmani","Mario Rui","Andre Zambo Anguissa","Stanislav Lobotka","Piotr Zielinski","Matteo Politano","Victor Osimhen","Khvicha Kvaratskhelia"],
     "lineup_b_names":["Wojciech Szczesny","Danilo","Leonardo Bonucci","Alex Sandro","Mattia De Sciglio","Weston McKennie","Adrien Rabiot","Manuel Locatelli","Angel Di Maria","Dusan Vlahovic","Federico Chiesa"]},
    {"match_id":"serie-a-napoli-title-2023","date":"2023-05-04","competition":"Serie A","season":"2022-23",
     "opponent_a":"Udinese","opponent_b":"Napoli","score":"1-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Marco Silvestri","Rodrigo Becao","Jaka Bijol","Destiny Udogie","Nahuel Molina","Roberto Pereyra","Walace","Lazar Samardzic","Sandi Lovric","Beto","Gerard Deulofeu"],
     "lineup_b_names":["Alex Meret","Giovanni Di Lorenzo","Min-jae Kim","Amir Rrahmani","Mario Rui","Andre Zambo Anguissa","Stanislav Lobotka","Piotr Zielinski","Matteo Politano","Victor Osimhen","Khvicha Kvaratskhelia"]},
    # More from the 2024-25 season
    {"match_id":"ucl-r16-2025-barca-psg","date":"2025-02-11","competition":"UEFA Champions League","season":"2024-25",
     "opponent_a":"Barcelona","opponent_b":"Paris Saint-Germain","score":"3-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Inaki Pena","Jules Kounde","Pau Cubarsi","Ronald Araujo","Alejandro Balde","Pedri","Marc Casado","Dani Olmo","Lamine Yamal","Robert Lewandowski","Raphinha"],
     "lineup_b_names":["Gianluigi Donnarumma","Achraf Hakimi","Marquinhos","Presnel Kimpembe","Nuno Mendes","Vitinha","Joao Neves","Warren Zaire-Emery","Ousmane Dembele","Kylian Mbappe","Bradley Barcola"]},
    {"match_id":"epl-arsenal-liverpool-2024","date":"2024-10-27","competition":"Premier League","season":"2024-25",
     "opponent_a":"Arsenal","opponent_b":"Liverpool","score":"2-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["David Raya","Ben White","William Saliba","Gabriel Magalhaes","Jurrien Timber","Declan Rice","Thomas Partey","Martin Odegaard","Bukayo Saka","Kai Havertz","Gabriel Martinelli"],
     "lineup_b_names":["Alisson","Trent Alexander-Arnold","Ibrahima Konate","Virgil van Dijk","Andrew Robertson","Ryan Gravenberch","Alexis Mac Allister","Dominik Szoboszlai","Mohamed Salah","Darwin Nunez","Luis Diaz"]},
    {"match_id":"epl-newcastle-city-2023","date":"2023-01-21","competition":"Premier League","season":"2022-23",
     "opponent_a":"Newcastle United","opponent_b":"Manchester City","score":"0-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Nick Pope","Kieran Trippier","Sven Botman","Fabian Schar","Dan Burn","Joelinton","Bruno Guimaraes","Sean Longstaff","Miguel Almiron","Callum Wilson","Alexander Isak"],
     "lineup_b_names":["Ederson","Kyle Walker","Ruben Dias","Manuel Akanji","Nathan Ake","Rodri","Kevin De Bruyne","Bernardo Silva","Riyad Mahrez","Erling Haaland","Phil Foden"]},
    {"match_id":"epl-brighton-mancity-2023","date":"2023-05-24","competition":"Premier League","season":"2022-23",
     "opponent_a":"Brighton","opponent_b":"Manchester City","score":"1-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Jason Steele","Tariq Lamptey","Lewis Dunk","Adam Webster","Pervis Estupinan","Moises Caicedo","Alexis Mac Allister","Julio Enciso","Pascal Gross","Evan Ferguson","Kaoru Mitoma"],
     "lineup_b_names":["Ederson","Kyle Walker","Ruben Dias","Manuel Akanji","Nathan Ake","Rodri","Ilkay Gundogan","Bernardo Silva","Jack Grealish","Erling Haaland","Phil Foden"]},
    {"match_id":"epl-villa-city-2024","date":"2024-04-03","competition":"Premier League","season":"2023-24",
     "opponent_a":"Aston Villa","opponent_b":"Manchester City","score":"0-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Emiliano Martinez","Matty Cash","Ezri Konsa","Pau Torres","Lucas Digne","Youri Tielemans","Boubacar Kamara","John McGinn","Leon Bailey","Ollie Watkins","Moussa Diaby"],
     "lineup_b_names":["Ederson","Kyle Walker","Ruben Dias","Josko Gvardiol","Nathan Ake","Rodri","Kevin De Bruyne","Bernardo Silva","Phil Foden","Erling Haaland","Jeremy Doku"]},
    # More UCL group/round matches
    {"match_id":"ucl-group-2024-dortmund-barca","date":"2024-12-11","competition":"UEFA Champions League","season":"2024-25",
     "opponent_a":"Borussia Dortmund","opponent_b":"Barcelona","score":"2-3",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Gregor Kobel","Julian Ryerson","Waldemar Anton","Nico Schlotterbeck","Ramy Bensebaini","Emre Can","Felix Nmecha","Julian Brandt","Jamie Bynoe-Gittens","Serhou Guirassy","Donyell Malen"],
     "lineup_b_names":["Inaki Pena","Jules Kounde","Pau Cubarsi","Inigo Martinez","Alejandro Balde","Pedri","Marc Casado","Dani Olmo","Lamine Yamal","Robert Lewandowski","Raphinha"]},
    {"match_id":"ucl-group-2024-city-feyenoord","date":"2024-11-26","competition":"UEFA Champions League","season":"2024-25",
     "opponent_a":"Manchester City","opponent_b":"Feyenoord","score":"3-3",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Ederson","Kyle Walker","Ruben Dias","Josko Gvardiol","Rico Lewis","Rodri","Ilkay Gundogan","Bernardo Silva","Savinho","Erling Haaland","Jack Grealish"],
     "lineup_b_names":["Timon Wellenreuther","Jordan Lotomba","Gernot Trauner","David Hancko","Hugo Bueno","Quinten Timber","Hwang In-beom","Antoni Milambo","Igor Paixao","Santiago Gimenez","Anis Hadj Moussa"]},
    # Cup Finals
    {"match_id":"fa-cup-final-2022","date":"2022-05-14","competition":"FA Cup Final","season":"2021-22",
     "opponent_a":"Chelsea","opponent_b":"Liverpool","score":"0-0 (5-6 pen)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Edouard Mendy","Cesar Azpilicueta","Thiago Silva","Antonio Rudiger","Marcos Alonso","N'Golo Kante","Jorginho","Mason Mount","Christian Pulisic","Kai Havertz","Romelu Lukaku"],
     "lineup_b_names":["Alisson","Trent Alexander-Arnold","Ibrahima Konate","Virgil van Dijk","Andrew Robertson","Fabinho","Thiago Alcantara","Jordan Henderson","Mohamed Salah","Sadio Mane","Luis Diaz"]},
    {"match_id":"copa-del-rey-final-2024","date":"2024-04-06","competition":"Copa del Rey Final","season":"2023-24",
     "opponent_a":"Athletic Bilbao","opponent_b":"Mallorca","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Unai Simon","Oscar De Marcos","Dani Vivian","Aitor Paredes","Yuri Berchiche","Oihan Sancet","Mikel Vesga","Iker Muniain","Nico Williams","Inaki Williams","Mikel Oyarzabal"],
     "lineup_b_names":["Predrag Rajkovic","Pablo Maffeo","Antonio Raillo","Valjent","Jaume Costa","Manu Morlanes","Antonio Sanchez","Dani Rodriguez","Sergi Darder","Vedat Muriqi","Abdon Prats"]},
    {"match_id":"dfb-pokal-final-2024","date":"2024-05-25","competition":"DFB-Pokal Final","season":"2023-24",
     "opponent_a":"Bayer Leverkusen","opponent_b":"Kaiserslautern","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Lukas Hradecky","Odilon Kossounou","Jonathan Tah","Edmond Tapsoba","Alejandro Grimaldo","Robert Andrich","Granit Xhaka","Florian Wirtz","Jeremie Frimpong","Victor Boniface","Amine Adli"],
     "lineup_b_names":["Julian Krahl","Jean Zimmer","Boris Tomiak","Robin Bormuth","Hendrick Zuck","Marlon Ritter","Phillipp Hercher","Kenny Redondo","Aaron Opoku","Ragnar Ache","Terrence Boyd"]},
    # More derbies from different leagues
    {"match_id":"superclasico-2018","date":"2018-12-09","competition":"Copa Libertadores Final","season":"2018",
     "opponent_a":"River Plate","opponent_b":"Boca Juniors","score":"3-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Franco Armani","Gonzalo Montiel","Lucas Martinez Quarta","Javier Pinola","Milton Casco","Enzo Perez","Exequiel Palacios","Leonardo Ponzio","Ignacio Fernandez","Gonzalo Martinez","Rafael Santos Borre"],
     "lineup_b_names":["Esteban Andrada","Leonardo Jara","Lisandro Lopez","Carlos Izquierdoz","Emmanuel Mas","Nandez","Wilmar Barrios","Pablo Perez","Sebastian Villa","Carlos Tevez","Dario Benedetto"]},
    {"match_id":"clasico-2024-10-26","date":"2024-10-26","competition":"La Liga","season":"2024-25",
     "opponent_a":"Real Madrid","opponent_b":"Barcelona","score":"0-4",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Andriy Lunin","Lucas Vazquez","Antonio Rudiger","Eder Militao","Ferland Mendy","Luka Modric","Federico Valverde","Jude Bellingham","Rodrygo","Kylian Mbappe","Vinicius Junior"],
     "lineup_b_names":["Inaki Pena","Jules Kounde","Pau Cubarsi","Inigo Martinez","Alejandro Balde","Pedri","Marc Casado","Dani Olmo","Lamine Yamal","Robert Lewandowski","Raphinha"]},
    # Asian Cup
    {"match_id":"asian-cup-final-2019","date":"2019-02-01","competition":"AFC Asian Cup Final","season":"2019",
     "opponent_a":"Japan","opponent_b":"Qatar","score":"1-3",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Shuichi Gonda","Hiroki Sakai","Maya Yoshida","Takehiro Tomiyasu","Yuto Nagatomo","Haraguchi","Shibasaki","Endo","Doan","Osako","Minamino"],
     "lineup_b_names":["Saad Al Sheeb","Pedro Miguel","Bassam Al-Rawi","Abdelkarim Hassan","Tarek Salman","Assim Madibo","Karim Boudiaf","Akram Afif","Abdulaziz Hatem","Almoez Ali","Hassan Al-Haydos"]},
    # More World Cup 2022
    {"match_id":"wc-group-2022-cameroon-brazil","date":"2022-12-02","competition":"FIFA World Cup Group Stage","season":"2022",
     "opponent_a":"Cameroon","opponent_b":"Brazil","score":"1-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Devis Epassy","Collins Fai","Jean-Charles Castelletto","Enzo Ebosse","Nouhou Tolo","Pierre Kunde","Andre-Frank Zambo Anguissa","Martin Hongla","Karl Toko Ekambi","Vincent Aboubakar","Bryan Mbeumo"],
     "lineup_b_names":["Ederson","Dani Alves","Eder Militao","Bremer","Alex Telles","Fabinho","Fred","Rodrygo","Antony","Gabriel Martinelli","Pedro"]},
    {"match_id":"wc-group-2022-saudi-argentina","date":"2022-11-26","competition":"FIFA World Cup Group Stage","season":"2022",
     "opponent_a":"Argentina","opponent_b":"Mexico","score":"2-0",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Emiliano Martinez","Nahuel Molina","Cristian Romero","Nicolas Otamendi","Marcos Acuna","Rodrigo De Paul","Guido Rodriguez","Enzo Fernandez","Angel Di Maria","Lionel Messi","Lautaro Martinez"],
     "lineup_b_names":["Guillermo Ochoa","Jorge Sanchez","Cesar Montes","Hector Moreno","Jesus Gallardo","Edson Alvarez","Luis Chavez","Orbelin Pineda","Hirving Lozano","Alexis Vega","Henry Martin"]},
    # Memorable league matches
    {"match_id":"epl-tottenham-ajax-2019","date":"2019-05-08","competition":"UEFA Champions League Semi-Final","season":"2018-19",
     "opponent_a":"Tottenham Hotspur","opponent_b":"Ajax","score":"3-2 (agg 3-3, away goals)",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Hugo Lloris","Kieran Trippier","Toby Alderweireld","Jan Vertonghen","Danny Rose","Moussa Sissoko","Victor Wanyama","Dele Alli","Christian Eriksen","Son Heung-min","Lucas Moura"],
     "lineup_b_names":["Andre Onana","Joel Veltman","Matthijs de Ligt","Daley Blind","Nicolas Tagliafico","Lasse Schone","Frenkie de Jong","Donny van de Beek","Hakim Ziyech","Dusan Tadic","David Neres"]},
    {"match_id":"epl-wolves-city-2023","date":"2023-09-30","competition":"Premier League","season":"2023-24",
     "opponent_a":"Wolverhampton","opponent_b":"Manchester City","score":"2-1",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Jose Sa","Nelson Semedo","Craig Dawson","Max Kilman","Rayan Ait-Nouri","Joao Gomes","Matheus Nunes","Pedro Neto","Pablo Sarabia","Hwang Hee-chan","Matheus Cunha"],
     "lineup_b_names":["Ederson","Kyle Walker","Ruben Dias","Manuel Akanji","Nathan Ake","Rodri","Mateo Kovacic","Bernardo Silva","Phil Foden","Erling Haaland","Jeremy Doku"]},
    {"match_id":"la-liga-girona-barca-2024","date":"2024-01-20","competition":"La Liga","season":"2023-24",
     "opponent_a":"Girona","opponent_b":"Barcelona","score":"4-2",
     "lineup_a_ids":z,"lineup_b_ids":z,
     "lineup_a_names":["Paulo Gazzaniga","Arnau Martinez","Daley Blind","Savinho","Miguel Gutierrez","Aleix Garcia","Ivan Martin","Oriol Romeu","Bryan Gil","Artem Dovbyk","Viktor Tsygankov"],
     "lineup_b_names":["Marc-Andre ter Stegen","Jules Kounde","Ronald Araujo","Inigo Martinez","Alejandro Balde","Pedri","Frenkie de Jong","Gavi","Ferran Torres","Robert Lewandowski","Joao Felix"]},
]

# Filter duplicates
new_matches = [m for m in more if m["match_id"] not in existing_ids]
existing.extend(new_matches)

print(f"Added {len(new_matches)} new matches")
print(f"Total matches: {len(existing)}")

with open("/Users/jasur/workspace/football/data/matches_db.json", "w") as f:
    json.dump(existing, f, indent=2, ensure_ascii=False)
print("matches_db.json updated successfully!")
